! ===================================================================================================
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these 
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary. 
! ===================================================================================================
! This code was generated by Write_ChckOutLst.m at 29-Sep-2015 10:23:41.


     ! Parameters related to output length (number of characters allowed in the output data headers):

   INTEGER(IntKi), PARAMETER      :: OutStrLenM1 = ChanLen - 1


     ! Indices for computing output channels:
     ! NOTES: 
     !    (1) These parameters are in the order stored in "OutListParameters.xlsx"
     !    (2) Array AllOuts() must be dimensioned to the value of the largest output parameter

     !  Time: 

   INTEGER(IntKi), PARAMETER      :: Time      =   0


     ! Reaction Loads:

   INTEGER(IntKi), PARAMETER      :: RootFxr   =   1
   INTEGER(IntKi), PARAMETER      :: RootFyr   =   2
   INTEGER(IntKi), PARAMETER      :: RootFzr   =   3
   INTEGER(IntKi), PARAMETER      :: RootMxr   =   4
   INTEGER(IntKi), PARAMETER      :: RootMyr   =   5
   INTEGER(IntKi), PARAMETER      :: RootMzr   =   6


     ! Tip Motions:

   INTEGER(IntKi), PARAMETER      :: TipTDxr   =   7
   INTEGER(IntKi), PARAMETER      :: TipTDyr   =   8
   INTEGER(IntKi), PARAMETER      :: TipTDzr   =   9
   INTEGER(IntKi), PARAMETER      :: TipRDxr   =  10
   INTEGER(IntKi), PARAMETER      :: TipRDyr   =  11
   INTEGER(IntKi), PARAMETER      :: TipRDzr   =  12
   INTEGER(IntKi), PARAMETER      :: TipTVXg   =  13
   INTEGER(IntKi), PARAMETER      :: TipTVYg   =  14
   INTEGER(IntKi), PARAMETER      :: TipTVZg   =  15
   INTEGER(IntKi), PARAMETER      :: TipRVXg   =  16
   INTEGER(IntKi), PARAMETER      :: TipRVYg   =  17
   INTEGER(IntKi), PARAMETER      :: TipRVZg   =  18
   INTEGER(IntKi), PARAMETER      :: TipTAXg   =  19
   INTEGER(IntKi), PARAMETER      :: TipTAYg   =  20
   INTEGER(IntKi), PARAMETER      :: TipTAZg   =  21
   INTEGER(IntKi), PARAMETER      :: TipRAXg   =  22
   INTEGER(IntKi), PARAMETER      :: TipRAYg   =  23
   INTEGER(IntKi), PARAMETER      :: TipRAZg   =  24


     ! Sectional Loads:

   INTEGER(IntKi), PARAMETER      :: N1Fxl     =  25
   INTEGER(IntKi), PARAMETER      :: N1Fyl     =  26
   INTEGER(IntKi), PARAMETER      :: N1Fzl     =  27
   INTEGER(IntKi), PARAMETER      :: N2Fxl     =  28
   INTEGER(IntKi), PARAMETER      :: N2Fyl     =  29
   INTEGER(IntKi), PARAMETER      :: N2Fzl     =  30
   INTEGER(IntKi), PARAMETER      :: N3Fxl     =  31
   INTEGER(IntKi), PARAMETER      :: N3Fyl     =  32
   INTEGER(IntKi), PARAMETER      :: N3Fzl     =  33
   INTEGER(IntKi), PARAMETER      :: N4Fxl     =  34
   INTEGER(IntKi), PARAMETER      :: N4Fyl     =  35
   INTEGER(IntKi), PARAMETER      :: N4Fzl     =  36
   INTEGER(IntKi), PARAMETER      :: N5Fxl     =  37
   INTEGER(IntKi), PARAMETER      :: N5Fyl     =  38
   INTEGER(IntKi), PARAMETER      :: N5Fzl     =  39
   INTEGER(IntKi), PARAMETER      :: N6Fxl     =  40
   INTEGER(IntKi), PARAMETER      :: N6Fyl     =  41
   INTEGER(IntKi), PARAMETER      :: N6Fzl     =  42
   INTEGER(IntKi), PARAMETER      :: N7Fxl     =  43
   INTEGER(IntKi), PARAMETER      :: N7Fyl     =  44
   INTEGER(IntKi), PARAMETER      :: N7Fzl     =  45
   INTEGER(IntKi), PARAMETER      :: N8Fxl     =  46
   INTEGER(IntKi), PARAMETER      :: N8Fyl     =  47
   INTEGER(IntKi), PARAMETER      :: N8Fzl     =  48
   INTEGER(IntKi), PARAMETER      :: N9Fxl     =  49
   INTEGER(IntKi), PARAMETER      :: N9Fyl     =  50
   INTEGER(IntKi), PARAMETER      :: N9Fzl     =  51
   INTEGER(IntKi), PARAMETER      :: N1Mxl     =  52
   INTEGER(IntKi), PARAMETER      :: N1Myl     =  53
   INTEGER(IntKi), PARAMETER      :: N1Mzl     =  54
   INTEGER(IntKi), PARAMETER      :: N2Mxl     =  55
   INTEGER(IntKi), PARAMETER      :: N2Myl     =  56
   INTEGER(IntKi), PARAMETER      :: N2Mzl     =  57
   INTEGER(IntKi), PARAMETER      :: N3Mxl     =  58
   INTEGER(IntKi), PARAMETER      :: N3Myl     =  59
   INTEGER(IntKi), PARAMETER      :: N3Mzl     =  60
   INTEGER(IntKi), PARAMETER      :: N4Mxl     =  61
   INTEGER(IntKi), PARAMETER      :: N4Myl     =  62
   INTEGER(IntKi), PARAMETER      :: N4Mzl     =  63
   INTEGER(IntKi), PARAMETER      :: N5Mxl     =  64
   INTEGER(IntKi), PARAMETER      :: N5Myl     =  65
   INTEGER(IntKi), PARAMETER      :: N5Mzl     =  66
   INTEGER(IntKi), PARAMETER      :: N6Mxl     =  67
   INTEGER(IntKi), PARAMETER      :: N6Myl     =  68
   INTEGER(IntKi), PARAMETER      :: N6Mzl     =  69
   INTEGER(IntKi), PARAMETER      :: N7Mxl     =  70
   INTEGER(IntKi), PARAMETER      :: N7Myl     =  71
   INTEGER(IntKi), PARAMETER      :: N7Mzl     =  72
   INTEGER(IntKi), PARAMETER      :: N8Mxl     =  73
   INTEGER(IntKi), PARAMETER      :: N8Myl     =  74
   INTEGER(IntKi), PARAMETER      :: N8Mzl     =  75
   INTEGER(IntKi), PARAMETER      :: N9Mxl     =  76
   INTEGER(IntKi), PARAMETER      :: N9Myl     =  77
   INTEGER(IntKi), PARAMETER      :: N9Mzl     =  78


     ! Sectional Motions:

   INTEGER(IntKi), PARAMETER      :: N1TDxr    =  79
   INTEGER(IntKi), PARAMETER      :: N1TDyr    =  80
   INTEGER(IntKi), PARAMETER      :: N1TDzr    =  81
   INTEGER(IntKi), PARAMETER      :: N2TDxr    =  82
   INTEGER(IntKi), PARAMETER      :: N2TDyr    =  83
   INTEGER(IntKi), PARAMETER      :: N2TDzr    =  84
   INTEGER(IntKi), PARAMETER      :: N3TDxr    =  85
   INTEGER(IntKi), PARAMETER      :: N3TDyr    =  86
   INTEGER(IntKi), PARAMETER      :: N3TDzr    =  87
   INTEGER(IntKi), PARAMETER      :: N4TDxr    =  88
   INTEGER(IntKi), PARAMETER      :: N4TDyr    =  89
   INTEGER(IntKi), PARAMETER      :: N4TDzr    =  90
   INTEGER(IntKi), PARAMETER      :: N5TDxr    =  91
   INTEGER(IntKi), PARAMETER      :: N5TDyr    =  92
   INTEGER(IntKi), PARAMETER      :: N5TDzr    =  93
   INTEGER(IntKi), PARAMETER      :: N6TDxr    =  94
   INTEGER(IntKi), PARAMETER      :: N6TDyr    =  95
   INTEGER(IntKi), PARAMETER      :: N6TDzr    =  96
   INTEGER(IntKi), PARAMETER      :: N7TDxr    =  97
   INTEGER(IntKi), PARAMETER      :: N7TDyr    =  98
   INTEGER(IntKi), PARAMETER      :: N7TDzr    =  99
   INTEGER(IntKi), PARAMETER      :: N8TDxr    = 100
   INTEGER(IntKi), PARAMETER      :: N8TDyr    = 101
   INTEGER(IntKi), PARAMETER      :: N8TDzr    = 102
   INTEGER(IntKi), PARAMETER      :: N9TDxr    = 103
   INTEGER(IntKi), PARAMETER      :: N9TDyr    = 104
   INTEGER(IntKi), PARAMETER      :: N9TDzr    = 105
   INTEGER(IntKi), PARAMETER      :: N1RDxr    = 106
   INTEGER(IntKi), PARAMETER      :: N1RDyr    = 107
   INTEGER(IntKi), PARAMETER      :: N1RDzr    = 108
   INTEGER(IntKi), PARAMETER      :: N2RDxr    = 109
   INTEGER(IntKi), PARAMETER      :: N2RDyr    = 110
   INTEGER(IntKi), PARAMETER      :: N2RDzr    = 111
   INTEGER(IntKi), PARAMETER      :: N3RDxr    = 112
   INTEGER(IntKi), PARAMETER      :: N3RDyr    = 113
   INTEGER(IntKi), PARAMETER      :: N3RDzr    = 114
   INTEGER(IntKi), PARAMETER      :: N4RDxr    = 115
   INTEGER(IntKi), PARAMETER      :: N4RDyr    = 116
   INTEGER(IntKi), PARAMETER      :: N4RDzr    = 117
   INTEGER(IntKi), PARAMETER      :: N5RDxr    = 118
   INTEGER(IntKi), PARAMETER      :: N5RDyr    = 119
   INTEGER(IntKi), PARAMETER      :: N5RDzr    = 120
   INTEGER(IntKi), PARAMETER      :: N6RDxr    = 121
   INTEGER(IntKi), PARAMETER      :: N6RDyr    = 122
   INTEGER(IntKi), PARAMETER      :: N6RDzr    = 123
   INTEGER(IntKi), PARAMETER      :: N7RDxr    = 124
   INTEGER(IntKi), PARAMETER      :: N7RDyr    = 125
   INTEGER(IntKi), PARAMETER      :: N7RDzr    = 126
   INTEGER(IntKi), PARAMETER      :: N8RDxr    = 127
   INTEGER(IntKi), PARAMETER      :: N8RDyr    = 128
   INTEGER(IntKi), PARAMETER      :: N8RDzr    = 129
   INTEGER(IntKi), PARAMETER      :: N9RDxr    = 130
   INTEGER(IntKi), PARAMETER      :: N9RDyr    = 131
   INTEGER(IntKi), PARAMETER      :: N9RDzr    = 132
   INTEGER(IntKi), PARAMETER      :: N1TVXg    = 133
   INTEGER(IntKi), PARAMETER      :: N1TVYg    = 134
   INTEGER(IntKi), PARAMETER      :: N1TVZg    = 135
   INTEGER(IntKi), PARAMETER      :: N2TVXg    = 136
   INTEGER(IntKi), PARAMETER      :: N2TVYg    = 137
   INTEGER(IntKi), PARAMETER      :: N2TVZg    = 138
   INTEGER(IntKi), PARAMETER      :: N3TVXg    = 139
   INTEGER(IntKi), PARAMETER      :: N3TVYg    = 140
   INTEGER(IntKi), PARAMETER      :: N3TVZg    = 141
   INTEGER(IntKi), PARAMETER      :: N4TVXg    = 142
   INTEGER(IntKi), PARAMETER      :: N4TVYg    = 143
   INTEGER(IntKi), PARAMETER      :: N4TVZg    = 144
   INTEGER(IntKi), PARAMETER      :: N5TVXg    = 145
   INTEGER(IntKi), PARAMETER      :: N5TVYg    = 146
   INTEGER(IntKi), PARAMETER      :: N5TVZg    = 147
   INTEGER(IntKi), PARAMETER      :: N6TVXg    = 148
   INTEGER(IntKi), PARAMETER      :: N6TVYg    = 149
   INTEGER(IntKi), PARAMETER      :: N6TVZg    = 150
   INTEGER(IntKi), PARAMETER      :: N7TVXg    = 151
   INTEGER(IntKi), PARAMETER      :: N7TVYg    = 152
   INTEGER(IntKi), PARAMETER      :: N7TVZg    = 153
   INTEGER(IntKi), PARAMETER      :: N8TVXg    = 154
   INTEGER(IntKi), PARAMETER      :: N8TVYg    = 155
   INTEGER(IntKi), PARAMETER      :: N8TVZg    = 156
   INTEGER(IntKi), PARAMETER      :: N9TVXg    = 157
   INTEGER(IntKi), PARAMETER      :: N9TVYg    = 158
   INTEGER(IntKi), PARAMETER      :: N9TVZg    = 159
   INTEGER(IntKi), PARAMETER      :: N1RVXg    = 160
   INTEGER(IntKi), PARAMETER      :: N1RVYg    = 161
   INTEGER(IntKi), PARAMETER      :: N1RVZg    = 162
   INTEGER(IntKi), PARAMETER      :: N2RVXg    = 163
   INTEGER(IntKi), PARAMETER      :: N2RVYg    = 164
   INTEGER(IntKi), PARAMETER      :: N2RVZg    = 165
   INTEGER(IntKi), PARAMETER      :: N3RVXg    = 166
   INTEGER(IntKi), PARAMETER      :: N3RVYg    = 167
   INTEGER(IntKi), PARAMETER      :: N3RVZg    = 168
   INTEGER(IntKi), PARAMETER      :: N4RVXg    = 169
   INTEGER(IntKi), PARAMETER      :: N4RVYg    = 170
   INTEGER(IntKi), PARAMETER      :: N4RVZg    = 171
   INTEGER(IntKi), PARAMETER      :: N5RVXg    = 172
   INTEGER(IntKi), PARAMETER      :: N5RVYg    = 173
   INTEGER(IntKi), PARAMETER      :: N5RVZg    = 174
   INTEGER(IntKi), PARAMETER      :: N6RVXg    = 175
   INTEGER(IntKi), PARAMETER      :: N6RVYg    = 176
   INTEGER(IntKi), PARAMETER      :: N6RVZg    = 177
   INTEGER(IntKi), PARAMETER      :: N7RVXg    = 178
   INTEGER(IntKi), PARAMETER      :: N7RVYg    = 179
   INTEGER(IntKi), PARAMETER      :: N7RVZg    = 180
   INTEGER(IntKi), PARAMETER      :: N8RVXg    = 181
   INTEGER(IntKi), PARAMETER      :: N8RVYg    = 182
   INTEGER(IntKi), PARAMETER      :: N8RVZg    = 183
   INTEGER(IntKi), PARAMETER      :: N9RVXg    = 184
   INTEGER(IntKi), PARAMETER      :: N9RVYg    = 185
   INTEGER(IntKi), PARAMETER      :: N9RVZg    = 186
   INTEGER(IntKi), PARAMETER      :: N1TAXg    = 187
   INTEGER(IntKi), PARAMETER      :: N1TAYg    = 188
   INTEGER(IntKi), PARAMETER      :: N1TAZg    = 189
   INTEGER(IntKi), PARAMETER      :: N2TAXg    = 190
   INTEGER(IntKi), PARAMETER      :: N2TAYg    = 191
   INTEGER(IntKi), PARAMETER      :: N2TAZg    = 192
   INTEGER(IntKi), PARAMETER      :: N3TAXg    = 193
   INTEGER(IntKi), PARAMETER      :: N3TAYg    = 194
   INTEGER(IntKi), PARAMETER      :: N3TAZg    = 195
   INTEGER(IntKi), PARAMETER      :: N4TAXg    = 196
   INTEGER(IntKi), PARAMETER      :: N4TAYg    = 197
   INTEGER(IntKi), PARAMETER      :: N4TAZg    = 198
   INTEGER(IntKi), PARAMETER      :: N5TAXg    = 199
   INTEGER(IntKi), PARAMETER      :: N5TAYg    = 200
   INTEGER(IntKi), PARAMETER      :: N5TAZg    = 201
   INTEGER(IntKi), PARAMETER      :: N6TAXg    = 202
   INTEGER(IntKi), PARAMETER      :: N6TAYg    = 203
   INTEGER(IntKi), PARAMETER      :: N6TAZg    = 204
   INTEGER(IntKi), PARAMETER      :: N7TAXg    = 205
   INTEGER(IntKi), PARAMETER      :: N7TAYg    = 206
   INTEGER(IntKi), PARAMETER      :: N7TAZg    = 207
   INTEGER(IntKi), PARAMETER      :: N8TAXg    = 208
   INTEGER(IntKi), PARAMETER      :: N8TAYg    = 209
   INTEGER(IntKi), PARAMETER      :: N8TAZg    = 210
   INTEGER(IntKi), PARAMETER      :: N9TAXg    = 211
   INTEGER(IntKi), PARAMETER      :: N9TAYg    = 212
   INTEGER(IntKi), PARAMETER      :: N9TAZg    = 213
   INTEGER(IntKi), PARAMETER      :: N1RAXg    = 214
   INTEGER(IntKi), PARAMETER      :: N1RAYg    = 215
   INTEGER(IntKi), PARAMETER      :: N1RAZg    = 216
   INTEGER(IntKi), PARAMETER      :: N2RAXg    = 217
   INTEGER(IntKi), PARAMETER      :: N2RAYg    = 218
   INTEGER(IntKi), PARAMETER      :: N2RAZg    = 219
   INTEGER(IntKi), PARAMETER      :: N3RAXg    = 220
   INTEGER(IntKi), PARAMETER      :: N3RAYg    = 221
   INTEGER(IntKi), PARAMETER      :: N3RAZg    = 222
   INTEGER(IntKi), PARAMETER      :: N4RAXg    = 223
   INTEGER(IntKi), PARAMETER      :: N4RAYg    = 224
   INTEGER(IntKi), PARAMETER      :: N4RAZg    = 225
   INTEGER(IntKi), PARAMETER      :: N5RAXg    = 226
   INTEGER(IntKi), PARAMETER      :: N5RAYg    = 227
   INTEGER(IntKi), PARAMETER      :: N5RAZg    = 228
   INTEGER(IntKi), PARAMETER      :: N6RAXg    = 229
   INTEGER(IntKi), PARAMETER      :: N6RAYg    = 230
   INTEGER(IntKi), PARAMETER      :: N6RAZg    = 231
   INTEGER(IntKi), PARAMETER      :: N7RAXg    = 232
   INTEGER(IntKi), PARAMETER      :: N7RAYg    = 233
   INTEGER(IntKi), PARAMETER      :: N7RAZg    = 234
   INTEGER(IntKi), PARAMETER      :: N8RAXg    = 235
   INTEGER(IntKi), PARAMETER      :: N8RAYg    = 236
   INTEGER(IntKi), PARAMETER      :: N8RAZg    = 237
   INTEGER(IntKi), PARAMETER      :: N9RAXg    = 238
   INTEGER(IntKi), PARAMETER      :: N9RAYg    = 239
   INTEGER(IntKi), PARAMETER      :: N9RAZg    = 240


     ! Applied Loads:

   INTEGER(IntKi), PARAMETER      :: N1PFxl    = 241
   INTEGER(IntKi), PARAMETER      :: N1PFyl    = 242
   INTEGER(IntKi), PARAMETER      :: N1PFzl    = 243
   INTEGER(IntKi), PARAMETER      :: N2PFxl    = 244
   INTEGER(IntKi), PARAMETER      :: N2PFyl    = 245
   INTEGER(IntKi), PARAMETER      :: N2PFzl    = 246
   INTEGER(IntKi), PARAMETER      :: N3PFxl    = 247
   INTEGER(IntKi), PARAMETER      :: N3PFyl    = 248
   INTEGER(IntKi), PARAMETER      :: N3PFzl    = 249
   INTEGER(IntKi), PARAMETER      :: N4PFxl    = 250
   INTEGER(IntKi), PARAMETER      :: N4PFyl    = 251
   INTEGER(IntKi), PARAMETER      :: N4PFzl    = 252
   INTEGER(IntKi), PARAMETER      :: N5PFxl    = 253
   INTEGER(IntKi), PARAMETER      :: N5PFyl    = 254
   INTEGER(IntKi), PARAMETER      :: N5PFzl    = 255
   INTEGER(IntKi), PARAMETER      :: N6PFxl    = 256
   INTEGER(IntKi), PARAMETER      :: N6PFyl    = 257
   INTEGER(IntKi), PARAMETER      :: N6PFzl    = 258
   INTEGER(IntKi), PARAMETER      :: N7PFxl    = 259
   INTEGER(IntKi), PARAMETER      :: N7PFyl    = 260
   INTEGER(IntKi), PARAMETER      :: N7PFzl    = 261
   INTEGER(IntKi), PARAMETER      :: N8PFxl    = 262
   INTEGER(IntKi), PARAMETER      :: N8PFyl    = 263
   INTEGER(IntKi), PARAMETER      :: N8PFzl    = 264
   INTEGER(IntKi), PARAMETER      :: N9PFxl    = 265
   INTEGER(IntKi), PARAMETER      :: N9PFyl    = 266
   INTEGER(IntKi), PARAMETER      :: N9PFzl    = 267
   INTEGER(IntKi), PARAMETER      :: N1PMxl    = 268
   INTEGER(IntKi), PARAMETER      :: N1PMyl    = 269
   INTEGER(IntKi), PARAMETER      :: N1PMzl    = 270
   INTEGER(IntKi), PARAMETER      :: N2PMxl    = 271
   INTEGER(IntKi), PARAMETER      :: N2PMyl    = 272
   INTEGER(IntKi), PARAMETER      :: N2PMzl    = 273
   INTEGER(IntKi), PARAMETER      :: N3PMxl    = 274
   INTEGER(IntKi), PARAMETER      :: N3PMyl    = 275
   INTEGER(IntKi), PARAMETER      :: N3PMzl    = 276
   INTEGER(IntKi), PARAMETER      :: N4PMxl    = 277
   INTEGER(IntKi), PARAMETER      :: N4PMyl    = 278
   INTEGER(IntKi), PARAMETER      :: N4PMzl    = 279
   INTEGER(IntKi), PARAMETER      :: N5PMxl    = 280
   INTEGER(IntKi), PARAMETER      :: N5PMyl    = 281
   INTEGER(IntKi), PARAMETER      :: N5PMzl    = 282
   INTEGER(IntKi), PARAMETER      :: N6PMxl    = 283
   INTEGER(IntKi), PARAMETER      :: N6PMyl    = 284
   INTEGER(IntKi), PARAMETER      :: N6PMzl    = 285
   INTEGER(IntKi), PARAMETER      :: N7PMxl    = 286
   INTEGER(IntKi), PARAMETER      :: N7PMyl    = 287
   INTEGER(IntKi), PARAMETER      :: N7PMzl    = 288
   INTEGER(IntKi), PARAMETER      :: N8PMxl    = 289
   INTEGER(IntKi), PARAMETER      :: N8PMyl    = 290
   INTEGER(IntKi), PARAMETER      :: N8PMzl    = 291
   INTEGER(IntKi), PARAMETER      :: N9PMxl    = 292
   INTEGER(IntKi), PARAMETER      :: N9PMyl    = 293
   INTEGER(IntKi), PARAMETER      :: N9PMzl    = 294
   INTEGER(IntKi), PARAMETER      :: N1DFxl    = 295
   INTEGER(IntKi), PARAMETER      :: N1DFyl    = 296
   INTEGER(IntKi), PARAMETER      :: N1DFzl    = 297
   INTEGER(IntKi), PARAMETER      :: N2DFxl    = 298
   INTEGER(IntKi), PARAMETER      :: N2DFyl    = 299
   INTEGER(IntKi), PARAMETER      :: N2DFzl    = 300
   INTEGER(IntKi), PARAMETER      :: N3DFxl    = 301
   INTEGER(IntKi), PARAMETER      :: N3DFyl    = 302
   INTEGER(IntKi), PARAMETER      :: N3DFzl    = 303
   INTEGER(IntKi), PARAMETER      :: N4DFxl    = 304
   INTEGER(IntKi), PARAMETER      :: N4DFyl    = 305
   INTEGER(IntKi), PARAMETER      :: N4DFzl    = 306
   INTEGER(IntKi), PARAMETER      :: N5DFxl    = 307
   INTEGER(IntKi), PARAMETER      :: N5DFyl    = 308
   INTEGER(IntKi), PARAMETER      :: N5DFzl    = 309
   INTEGER(IntKi), PARAMETER      :: N6DFxl    = 310
   INTEGER(IntKi), PARAMETER      :: N6DFyl    = 311
   INTEGER(IntKi), PARAMETER      :: N6DFzl    = 312
   INTEGER(IntKi), PARAMETER      :: N7DFxl    = 313
   INTEGER(IntKi), PARAMETER      :: N7DFyl    = 314
   INTEGER(IntKi), PARAMETER      :: N7DFzl    = 315
   INTEGER(IntKi), PARAMETER      :: N8DFxl    = 316
   INTEGER(IntKi), PARAMETER      :: N8DFyl    = 317
   INTEGER(IntKi), PARAMETER      :: N8DFzl    = 318
   INTEGER(IntKi), PARAMETER      :: N9DFxl    = 319
   INTEGER(IntKi), PARAMETER      :: N9DFyl    = 320
   INTEGER(IntKi), PARAMETER      :: N9DFzl    = 321
   INTEGER(IntKi), PARAMETER      :: N1DMxl    = 322
   INTEGER(IntKi), PARAMETER      :: N1DMyl    = 323
   INTEGER(IntKi), PARAMETER      :: N1DMzl    = 324
   INTEGER(IntKi), PARAMETER      :: N2DMxl    = 325
   INTEGER(IntKi), PARAMETER      :: N2DMyl    = 326
   INTEGER(IntKi), PARAMETER      :: N2DMzl    = 327
   INTEGER(IntKi), PARAMETER      :: N3DMxl    = 328
   INTEGER(IntKi), PARAMETER      :: N3DMyl    = 329
   INTEGER(IntKi), PARAMETER      :: N3DMzl    = 330
   INTEGER(IntKi), PARAMETER      :: N4DMxl    = 331
   INTEGER(IntKi), PARAMETER      :: N4DMyl    = 332
   INTEGER(IntKi), PARAMETER      :: N4DMzl    = 333
   INTEGER(IntKi), PARAMETER      :: N5DMxl    = 334
   INTEGER(IntKi), PARAMETER      :: N5DMyl    = 335
   INTEGER(IntKi), PARAMETER      :: N5DMzl    = 336
   INTEGER(IntKi), PARAMETER      :: N6DMxl    = 337
   INTEGER(IntKi), PARAMETER      :: N6DMyl    = 338
   INTEGER(IntKi), PARAMETER      :: N6DMzl    = 339
   INTEGER(IntKi), PARAMETER      :: N7DMxl    = 340
   INTEGER(IntKi), PARAMETER      :: N7DMyl    = 341
   INTEGER(IntKi), PARAMETER      :: N7DMzl    = 342
   INTEGER(IntKi), PARAMETER      :: N8DMxl    = 343
   INTEGER(IntKi), PARAMETER      :: N8DMyl    = 344
   INTEGER(IntKi), PARAMETER      :: N8DMzl    = 345
   INTEGER(IntKi), PARAMETER      :: N9DMxl    = 346
   INTEGER(IntKi), PARAMETER      :: N9DMyl    = 347
   INTEGER(IntKi), PARAMETER      :: N9DMzl    = 348


     ! Pitch Actuator:

   INTEGER(IntKi), PARAMETER      :: PAngInp   = 349
   INTEGER(IntKi), PARAMETER      :: PAngAct   = 350
   INTEGER(IntKi), PARAMETER      :: PRatAct   = 351
   INTEGER(IntKi), PARAMETER      :: PAccAct   = 352


     ! The maximum number of output channels which can be output by the code.
   INTEGER(IntKi), PARAMETER      :: MaxOutPts = 352

!End of code generated by Matlab script
! ===================================================================================================
