!**********************************************************************************************************************************
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these 
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary. 
! This code was generated by Write_ChckOutLst.m at 29-Sep-2015 10:23:41.
!----------------------------------------------------------------------------------------------------------------------------------
SUBROUTINE SetOutParam(OutList, p, ErrStat, ErrMsg )
! This routine checks to see if any requested output channel names (stored in the OutList(:)) are invalid. It returns a 
! warning if any of the channels are not available outputs from the module.
!  It assigns the settings for OutParam(:) (i.e, the index, name, and units of the output channels, WriteOutput(:)).
!  the sign is set to 0 if the channel is invalid.
! It sets assumes the value p%NumOuts has been set before this routine has been called, and it sets the values of p%OutParam here.
!..................................................................................................................................

   IMPLICIT                        NONE

      ! Passed variables

   CHARACTER(ChanLen),        INTENT(IN)     :: OutList(:)                        ! The list out user-requested outputs
   TYPE(BD_ParameterType),    INTENT(INOUT)  :: p                                 ! The module parameters
   INTEGER(IntKi),            INTENT(OUT)    :: ErrStat                           ! The error status code
   CHARACTER(*),              INTENT(OUT)    :: ErrMsg                            ! The error message, if an error occurred

      ! Local variables

   INTEGER                      :: ErrStat2                                        ! temporary (local) error status
   INTEGER                      :: I                                               ! Generic loop-counting index
   INTEGER                      :: J                                               ! Generic loop-counting index
   INTEGER                      :: INDX                                            ! Index for valid arrays

   LOGICAL                      :: CheckOutListAgain                               ! Flag used to determine if output parameter starting with "M" is valid (or the negative of another parameter)
   LOGICAL                      :: InvalidOutput(0:MaxOutPts)                      ! This array determines if the output channel is valid for this configuration
   CHARACTER(ChanLen)           :: OutListTmp                                      ! A string to temporarily hold OutList(I)
   CHARACTER(*), PARAMETER      :: RoutineName = "SetOutParam"

   CHARACTER(OutStrLenM1), PARAMETER  :: ValidParamAry(352) =  (/ &                  ! This lists the names of the allowed parameters, which must be sorted alphabetically
                               "N1DFXL   ","N1DFYL   ","N1DFZL   ","N1DMXL   ","N1DMYL   ","N1DMZL   ","N1FXL    ", &
                               "N1FYL    ","N1FZL    ","N1MXL    ","N1MYL    ","N1MZL    ","N1PFXL   ","N1PFYL   ", &
                               "N1PFZL   ","N1PMXL   ","N1PMYL   ","N1PMZL   ","N1RAXG   ","N1RAYG   ","N1RAZG   ", &
                               "N1RDXR   ","N1RDYR   ","N1RDZR   ","N1RVXG   ","N1RVYG   ","N1RVZG   ","N1TAXG   ", &
                               "N1TAYG   ","N1TAZG   ","N1TDXR   ","N1TDYR   ","N1TDZR   ","N1TVXG   ","N1TVYG   ", &
                               "N1TVZG   ","N2DFXL   ","N2DFYL   ","N2DFZL   ","N2DMXL   ","N2DMYL   ","N2DMZL   ", &
                               "N2FXL    ","N2FYL    ","N2FZL    ","N2MXL    ","N2MYL    ","N2MZL    ","N2PFXL   ", &
                               "N2PFYL   ","N2PFZL   ","N2PMXL   ","N2PMYL   ","N2PMZL   ","N2RAXG   ","N2RAYG   ", &
                               "N2RAZG   ","N2RDXR   ","N2RDYR   ","N2RDZR   ","N2RVXG   ","N2RVYG   ","N2RVZG   ", &
                               "N2TAXG   ","N2TAYG   ","N2TAZG   ","N2TDXR   ","N2TDYR   ","N2TDZR   ","N2TVXG   ", &
                               "N2TVYG   ","N2TVZG   ","N3DFXL   ","N3DFYL   ","N3DFZL   ","N3DMXL   ","N3DMYL   ", &
                               "N3DMZL   ","N3FXL    ","N3FYL    ","N3FZL    ","N3MXL    ","N3MYL    ","N3MZL    ", &
                               "N3PFXL   ","N3PFYL   ","N3PFZL   ","N3PMXL   ","N3PMYL   ","N3PMZL   ","N3RAXG   ", &
                               "N3RAYG   ","N3RAZG   ","N3RDXR   ","N3RDYR   ","N3RDZR   ","N3RVXG   ","N3RVYG   ", &
                               "N3RVZG   ","N3TAXG   ","N3TAYG   ","N3TAZG   ","N3TDXR   ","N3TDYR   ","N3TDZR   ", &
                               "N3TVXG   ","N3TVYG   ","N3TVZG   ","N4DFXL   ","N4DFYL   ","N4DFZL   ","N4DMXL   ", &
                               "N4DMYL   ","N4DMZL   ","N4FXL    ","N4FYL    ","N4FZL    ","N4MXL    ","N4MYL    ", &
                               "N4MZL    ","N4PFXL   ","N4PFYL   ","N4PFZL   ","N4PMXL   ","N4PMYL   ","N4PMZL   ", &
                               "N4RAXG   ","N4RAYG   ","N4RAZG   ","N4RDXR   ","N4RDYR   ","N4RDZR   ","N4RVXG   ", &
                               "N4RVYG   ","N4RVZG   ","N4TAXG   ","N4TAYG   ","N4TAZG   ","N4TDXR   ","N4TDYR   ", &
                               "N4TDZR   ","N4TVXG   ","N4TVYG   ","N4TVZG   ","N5DFXL   ","N5DFYL   ","N5DFZL   ", &
                               "N5DMXL   ","N5DMYL   ","N5DMZL   ","N5FXL    ","N5FYL    ","N5FZL    ","N5MXL    ", &
                               "N5MYL    ","N5MZL    ","N5PFXL   ","N5PFYL   ","N5PFZL   ","N5PMXL   ","N5PMYL   ", &
                               "N5PMZL   ","N5RAXG   ","N5RAYG   ","N5RAZG   ","N5RDXR   ","N5RDYR   ","N5RDZR   ", &
                               "N5RVXG   ","N5RVYG   ","N5RVZG   ","N5TAXG   ","N5TAYG   ","N5TAZG   ","N5TDXR   ", &
                               "N5TDYR   ","N5TDZR   ","N5TVXG   ","N5TVYG   ","N5TVZG   ","N6DFXL   ","N6DFYL   ", &
                               "N6DFZL   ","N6DMXL   ","N6DMYL   ","N6DMZL   ","N6FXL    ","N6FYL    ","N6FZL    ", &
                               "N6MXL    ","N6MYL    ","N6MZL    ","N6PFXL   ","N6PFYL   ","N6PFZL   ","N6PMXL   ", &
                               "N6PMYL   ","N6PMZL   ","N6RAXG   ","N6RAYG   ","N6RAZG   ","N6RDXR   ","N6RDYR   ", &
                               "N6RDZR   ","N6RVXG   ","N6RVYG   ","N6RVZG   ","N6TAXG   ","N6TAYG   ","N6TAZG   ", &
                               "N6TDXR   ","N6TDYR   ","N6TDZR   ","N6TVXG   ","N6TVYG   ","N6TVZG   ","N7DFXL   ", &
                               "N7DFYL   ","N7DFZL   ","N7DMXL   ","N7DMYL   ","N7DMZL   ","N7FXL    ","N7FYL    ", &
                               "N7FZL    ","N7MXL    ","N7MYL    ","N7MZL    ","N7PFXL   ","N7PFYL   ","N7PFZL   ", &
                               "N7PMXL   ","N7PMYL   ","N7PMZL   ","N7RAXG   ","N7RAYG   ","N7RAZG   ","N7RDXR   ", &
                               "N7RDYR   ","N7RDZR   ","N7RVXG   ","N7RVYG   ","N7RVZG   ","N7TAXG   ","N7TAYG   ", &
                               "N7TAZG   ","N7TDXR   ","N7TDYR   ","N7TDZR   ","N7TVXG   ","N7TVYG   ","N7TVZG   ", &
                               "N8DFXL   ","N8DFYL   ","N8DFZL   ","N8DMXL   ","N8DMYL   ","N8DMZL   ","N8FXL    ", &
                               "N8FYL    ","N8FZL    ","N8MXL    ","N8MYL    ","N8MZL    ","N8PFXL   ","N8PFYL   ", &
                               "N8PFZL   ","N8PMXL   ","N8PMYL   ","N8PMZL   ","N8RAXG   ","N8RAYG   ","N8RAZG   ", &
                               "N8RDXR   ","N8RDYR   ","N8RDZR   ","N8RVXG   ","N8RVYG   ","N8RVZG   ","N8TAXG   ", &
                               "N8TAYG   ","N8TAZG   ","N8TDXR   ","N8TDYR   ","N8TDZR   ","N8TVXG   ","N8TVYG   ", &
                               "N8TVZG   ","N9DFXL   ","N9DFYL   ","N9DFZL   ","N9DMXL   ","N9DMYL   ","N9DMZL   ", &
                               "N9FXL    ","N9FYL    ","N9FZL    ","N9MXL    ","N9MYL    ","N9MZL    ","N9PFXL   ", &
                               "N9PFYL   ","N9PFZL   ","N9PMXL   ","N9PMYL   ","N9PMZL   ","N9RAXG   ","N9RAYG   ", &
                               "N9RAZG   ","N9RDXR   ","N9RDYR   ","N9RDZR   ","N9RVXG   ","N9RVYG   ","N9RVZG   ", &
                               "N9TAXG   ","N9TAYG   ","N9TAZG   ","N9TDXR   ","N9TDYR   ","N9TDZR   ","N9TVXG   ", &
                               "N9TVYG   ","N9TVZG   ","PACCACT  ","PANGACT  ","PANGINP  ","PRATACT  ","ROOTFXR  ", &
                               "ROOTFYR  ","ROOTFZR  ","ROOTMXR  ","ROOTMYR  ","ROOTMZR  ","TIPRAXG  ","TIPRAYG  ", &
                               "TIPRAZG  ","TIPRDXR  ","TIPRDYR  ","TIPRDZR  ","TIPRVXG  ","TIPRVYG  ","TIPRVZG  ", &
                               "TIPTAXG  ","TIPTAYG  ","TIPTAZG  ","TIPTDXR  ","TIPTDYR  ","TIPTDZR  ","TIPTVXG  ", &
                               "TIPTVYG  ","TIPTVZG  "/)
   INTEGER(IntKi), PARAMETER :: ParamIndxAry(352) =  (/ &                            ! This lists the index into AllOuts(:) of the allowed parameters ValidParamAry(:)
                                   N1DFxl ,    N1DFyl ,    N1DFzl ,    N1DMxl ,    N1DMyl ,    N1DMzl ,     N1Fxl , &
                                    N1Fyl ,     N1Fzl ,     N1Mxl ,     N1Myl ,     N1Mzl ,    N1PFxl ,    N1PFyl , &
                                   N1PFzl ,    N1PMxl ,    N1PMyl ,    N1PMzl ,    N1RAXg ,    N1RAYg ,    N1RAZg , &
                                   N1RDxr ,    N1RDyr ,    N1RDzr ,    N1RVXg ,    N1RVYg ,    N1RVZg ,    N1TAXg , &
                                   N1TAYg ,    N1TAZg ,    N1TDxr ,    N1TDyr ,    N1TDzr ,    N1TVXg ,    N1TVYg , &
                                   N1TVZg ,    N2DFxl ,    N2DFyl ,    N2DFzl ,    N2DMxl ,    N2DMyl ,    N2DMzl , &
                                    N2Fxl ,     N2Fyl ,     N2Fzl ,     N2Mxl ,     N2Myl ,     N2Mzl ,    N2PFxl , &
                                   N2PFyl ,    N2PFzl ,    N2PMxl ,    N2PMyl ,    N2PMzl ,    N2RAXg ,    N2RAYg , &
                                   N2RAZg ,    N2RDxr ,    N2RDyr ,    N2RDzr ,    N2RVXg ,    N2RVYg ,    N2RVZg , &
                                   N2TAXg ,    N2TAYg ,    N2TAZg ,    N2TDxr ,    N2TDyr ,    N2TDzr ,    N2TVXg , &
                                   N2TVYg ,    N2TVZg ,    N3DFxl ,    N3DFyl ,    N3DFzl ,    N3DMxl ,    N3DMyl , &
                                   N3DMzl ,     N3Fxl ,     N3Fyl ,     N3Fzl ,     N3Mxl ,     N3Myl ,     N3Mzl , &
                                   N3PFxl ,    N3PFyl ,    N3PFzl ,    N3PMxl ,    N3PMyl ,    N3PMzl ,    N3RAXg , &
                                   N3RAYg ,    N3RAZg ,    N3RDxr ,    N3RDyr ,    N3RDzr ,    N3RVXg ,    N3RVYg , &
                                   N3RVZg ,    N3TAXg ,    N3TAYg ,    N3TAZg ,    N3TDxr ,    N3TDyr ,    N3TDzr , &
                                   N3TVXg ,    N3TVYg ,    N3TVZg ,    N4DFxl ,    N4DFyl ,    N4DFzl ,    N4DMxl , &
                                   N4DMyl ,    N4DMzl ,     N4Fxl ,     N4Fyl ,     N4Fzl ,     N4Mxl ,     N4Myl , &
                                    N4Mzl ,    N4PFxl ,    N4PFyl ,    N4PFzl ,    N4PMxl ,    N4PMyl ,    N4PMzl , &
                                   N4RAXg ,    N4RAYg ,    N4RAZg ,    N4RDxr ,    N4RDyr ,    N4RDzr ,    N4RVXg , &
                                   N4RVYg ,    N4RVZg ,    N4TAXg ,    N4TAYg ,    N4TAZg ,    N4TDxr ,    N4TDyr , &
                                   N4TDzr ,    N4TVXg ,    N4TVYg ,    N4TVZg ,    N5DFxl ,    N5DFyl ,    N5DFzl , &
                                   N5DMxl ,    N5DMyl ,    N5DMzl ,     N5Fxl ,     N5Fyl ,     N5Fzl ,     N5Mxl , &
                                    N5Myl ,     N5Mzl ,    N5PFxl ,    N5PFyl ,    N5PFzl ,    N5PMxl ,    N5PMyl , &
                                   N5PMzl ,    N5RAXg ,    N5RAYg ,    N5RAZg ,    N5RDxr ,    N5RDyr ,    N5RDzr , &
                                   N5RVXg ,    N5RVYg ,    N5RVZg ,    N5TAXg ,    N5TAYg ,    N5TAZg ,    N5TDxr , &
                                   N5TDyr ,    N5TDzr ,    N5TVXg ,    N5TVYg ,    N5TVZg ,    N6DFxl ,    N6DFyl , &
                                   N6DFzl ,    N6DMxl ,    N6DMyl ,    N6DMzl ,     N6Fxl ,     N6Fyl ,     N6Fzl , &
                                    N6Mxl ,     N6Myl ,     N6Mzl ,    N6PFxl ,    N6PFyl ,    N6PFzl ,    N6PMxl , &
                                   N6PMyl ,    N6PMzl ,    N6RAXg ,    N6RAYg ,    N6RAZg ,    N6RDxr ,    N6RDyr , &
                                   N6RDzr ,    N6RVXg ,    N6RVYg ,    N6RVZg ,    N6TAXg ,    N6TAYg ,    N6TAZg , &
                                   N6TDxr ,    N6TDyr ,    N6TDzr ,    N6TVXg ,    N6TVYg ,    N6TVZg ,    N7DFxl , &
                                   N7DFyl ,    N7DFzl ,    N7DMxl ,    N7DMyl ,    N7DMzl ,     N7Fxl ,     N7Fyl , &
                                    N7Fzl ,     N7Mxl ,     N7Myl ,     N7Mzl ,    N7PFxl ,    N7PFyl ,    N7PFzl , &
                                   N7PMxl ,    N7PMyl ,    N7PMzl ,    N7RAXg ,    N7RAYg ,    N7RAZg ,    N7RDxr , &
                                   N7RDyr ,    N7RDzr ,    N7RVXg ,    N7RVYg ,    N7RVZg ,    N7TAXg ,    N7TAYg , &
                                   N7TAZg ,    N7TDxr ,    N7TDyr ,    N7TDzr ,    N7TVXg ,    N7TVYg ,    N7TVZg , &
                                   N8DFxl ,    N8DFyl ,    N8DFzl ,    N8DMxl ,    N8DMyl ,    N8DMzl ,     N8Fxl , &
                                    N8Fyl ,     N8Fzl ,     N8Mxl ,     N8Myl ,     N8Mzl ,    N8PFxl ,    N8PFyl , &
                                   N8PFzl ,    N8PMxl ,    N8PMyl ,    N8PMzl ,    N8RAXg ,    N8RAYg ,    N8RAZg , &
                                   N8RDxr ,    N8RDyr ,    N8RDzr ,    N8RVXg ,    N8RVYg ,    N8RVZg ,    N8TAXg , &
                                   N8TAYg ,    N8TAZg ,    N8TDxr ,    N8TDyr ,    N8TDzr ,    N8TVXg ,    N8TVYg , &
                                   N8TVZg ,    N9DFxl ,    N9DFyl ,    N9DFzl ,    N9DMxl ,    N9DMyl ,    N9DMzl , &
                                    N9Fxl ,     N9Fyl ,     N9Fzl ,     N9Mxl ,     N9Myl ,     N9Mzl ,    N9PFxl , &
                                   N9PFyl ,    N9PFzl ,    N9PMxl ,    N9PMyl ,    N9PMzl ,    N9RAXg ,    N9RAYg , &
                                   N9RAZg ,    N9RDxr ,    N9RDyr ,    N9RDzr ,    N9RVXg ,    N9RVYg ,    N9RVZg , &
                                   N9TAXg ,    N9TAYg ,    N9TAZg ,    N9TDxr ,    N9TDyr ,    N9TDzr ,    N9TVXg , &
                                   N9TVYg ,    N9TVZg ,   PAccAct ,   PAngAct ,   PAngInp ,   PRatAct ,   RootFxr , &
                                  RootFyr ,   RootFzr ,   RootMxr ,   RootMyr ,   RootMzr ,   TipRAXg ,   TipRAYg , &
                                  TipRAZg ,   TipRDxr ,   TipRDyr ,   TipRDzr ,   TipRVXg ,   TipRVYg ,   TipRVZg , &
                                  TipTAXg ,   TipTAYg ,   TipTAZg ,   TipTDxr ,   TipTDyr ,   TipTDzr ,   TipTVXg , &
                                  TipTVYg ,   TipTVZg /)
   CHARACTER(ChanLen), PARAMETER :: ParamUnitsAry(352) =  (/ &                     ! This lists the units corresponding to the allowed parameters
                               "(N/m)     ","(N/m)     ","(N/m)     ","(N-m/m)   ","(N-m/m)   ","(N-m/m)   ","(N)       ", &
                               "(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(N)       ","(N)       ", &
                               "(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ","(deg/s^2) ", &
                               "(-)       ","(-)       ","(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ","(m/s^2)   ", &
                               "(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ","(m)       ","(m/s)     ","(m/s)     ", &
                               "(m/s)     ","(N/m)     ","(N/m)     ","(N/m)     ","(N-m/m)   ","(N-m/m)   ","(N-m/m)   ", &
                               "(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(N)       ", &
                               "(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ", &
                               "(deg/s^2) ","(-)       ","(-)       ","(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ", &
                               "(m/s^2)   ","(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ","(m)       ","(m/s)     ", &
                               "(m/s)     ","(m/s)     ","(N/m)     ","(N/m)     ","(N/m)     ","(N-m/m)   ","(N-m/m)   ", &
                               "(N-m/m)   ","(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ", &
                               "(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ", &
                               "(deg/s^2) ","(deg/s^2) ","(-)       ","(-)       ","(-)       ","(deg/s)   ","(deg/s)   ", &
                               "(deg/s)   ","(m/s^2)   ","(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ","(m)       ", &
                               "(m/s)     ","(m/s)     ","(m/s)     ","(N/m)     ","(N/m)     ","(N/m)     ","(N-m/m)   ", &
                               "(N-m/m)   ","(N-m/m)   ","(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ", &
                               "(N-m)     ","(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ", &
                               "(deg/s^2) ","(deg/s^2) ","(deg/s^2) ","(-)       ","(-)       ","(-)       ","(deg/s)   ", &
                               "(deg/s)   ","(deg/s)   ","(m/s^2)   ","(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ", &
                               "(m)       ","(m/s)     ","(m/s)     ","(m/s)     ","(N/m)     ","(N/m)     ","(N/m)     ", &
                               "(N-m/m)   ","(N-m/m)   ","(N-m/m)   ","(N)       ","(N)       ","(N)       ","(N-m)     ", &
                               "(N-m)     ","(N-m)     ","(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ", &
                               "(N-m)     ","(deg/s^2) ","(deg/s^2) ","(deg/s^2) ","(-)       ","(-)       ","(-)       ", &
                               "(deg/s)   ","(deg/s)   ","(deg/s)   ","(m/s^2)   ","(m/s^2)   ","(m/s^2)   ","(m)       ", &
                               "(m)       ","(m)       ","(m/s)     ","(m/s)     ","(m/s)     ","(N/m)     ","(N/m)     ", &
                               "(N/m)     ","(N-m/m)   ","(N-m/m)   ","(N-m/m)   ","(N)       ","(N)       ","(N)       ", &
                               "(N-m)     ","(N-m)     ","(N-m)     ","(N)       ","(N)       ","(N)       ","(N-m)     ", &
                               "(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ","(deg/s^2) ","(-)       ","(-)       ", &
                               "(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ","(m/s^2)   ","(m/s^2)   ","(m/s^2)   ", &
                               "(m)       ","(m)       ","(m)       ","(m/s)     ","(m/s)     ","(m/s)     ","(N/m)     ", &
                               "(N/m)     ","(N/m)     ","(N-m/m)   ","(N-m/m)   ","(N-m/m)   ","(N)       ","(N)       ", &
                               "(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(N)       ","(N)       ","(N)       ", &
                               "(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ","(deg/s^2) ","(-)       ", &
                               "(-)       ","(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ","(m/s^2)   ","(m/s^2)   ", &
                               "(m/s^2)   ","(m)       ","(m)       ","(m)       ","(m/s)     ","(m/s)     ","(m/s)     ", &
                               "(N/m)     ","(N/m)     ","(N/m)     ","(N-m/m)   ","(N-m/m)   ","(N-m/m)   ","(N)       ", &
                               "(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(N)       ","(N)       ", &
                               "(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ","(deg/s^2) ", &
                               "(-)       ","(-)       ","(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ","(m/s^2)   ", &
                               "(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ","(m)       ","(m/s)     ","(m/s)     ", &
                               "(m/s)     ","(N/m)     ","(N/m)     ","(N/m)     ","(N-m/m)   ","(N-m/m)   ","(N-m/m)   ", &
                               "(N)       ","(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(N)       ", &
                               "(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ", &
                               "(deg/s^2) ","(-)       ","(-)       ","(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ", &
                               "(m/s^2)   ","(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ","(m)       ","(m/s)     ", &
                               "(m/s)     ","(m/s)     ","(deg/s^2) ","(deg)     ","(deg)     ","(deg/s)   ","(N)       ", &
                               "(N)       ","(N)       ","(N-m)     ","(N-m)     ","(N-m)     ","(deg/s^2) ","(deg/s^2) ", &
                               "(deg/s^2) ","(-)       ","(-)       ","(-)       ","(deg/s)   ","(deg/s)   ","(deg/s)   ", &
                               "(m/s^2)   ","(m/s^2)   ","(m/s^2)   ","(m)       ","(m)       ","(m)       ","(m/s)     ", &
                               "(m/s)     ","(m/s)     "/)


      ! Initialize values
   ErrStat = ErrID_None
   ErrMsg = ""
   InvalidOutput = .FALSE.


!   ..... Developer must add checking for invalid inputs here: .....

!   ................. End of validity checking .................


   !-------------------------------------------------------------------------------------------------
   ! Allocate and set index, name, and units for the output channels
   ! If a selected output channel is not available in this module, set error flag.
   !-------------------------------------------------------------------------------------------------

   ALLOCATE ( p%OutParam(0:p%NumOuts) , STAT=ErrStat2 )
   IF ( ErrStat2 /= 0_IntKi )  THEN
      CALL SetErrStat( ErrID_Fatal,"Error allocating memory for the BeamDyn OutParam array.", ErrStat, ErrMsg, RoutineName )
      RETURN
   ENDIF

      ! Set index, name, and units for the time output channel:

   p%OutParam(0)%Indx  = Time
   p%OutParam(0)%Name  = "Time"    ! OutParam(0) is the time channel by default.
   p%OutParam(0)%Units = "(s)"
   p%OutParam(0)%SignM = 1


      ! Set index, name, and units for all of the output channels.
      ! If a selected output channel is not available by this module set ErrStat = ErrID_Warn.

   DO I = 1,p%NumOuts

      p%OutParam(I)%Name  = OutList(I)
      OutListTmp          = OutList(I)

      ! Reverse the sign (+/-) of the output channel if the user prefixed the
      !   channel name with a "-", "_", "m", or "M" character indicating "minus".


      CheckOutListAgain = .FALSE.

      IF      ( INDEX( "-_", OutListTmp(1:1) ) > 0 ) THEN
         p%OutParam(I)%SignM = -1                         ! ex, "-TipDxc1" causes the sign of TipDxc1 to be switched.
         OutListTmp          = OutListTmp(2:)
      ELSE IF ( INDEX( "mM", OutListTmp(1:1) ) > 0 ) THEN ! We'll assume this is a variable name for now, (if not, we will check later if OutListTmp(2:) is also a variable name)
         CheckOutListAgain   = .TRUE.
         p%OutParam(I)%SignM = 1
      ELSE
         p%OutParam(I)%SignM = 1
      END IF

      CALL Conv2UC( OutListTmp )    ! Convert OutListTmp to upper case


      Indx = IndexCharAry( OutListTmp(1:OutStrLenM1), ValidParamAry )


         ! If it started with an "M" (CheckOutListAgain) we didn't find the value in our list (Indx < 1)

      IF ( CheckOutListAgain .AND. Indx < 1 ) THEN    ! Let's assume that "M" really meant "minus" and then test again
         p%OutParam(I)%SignM = -1                     ! ex, "MTipDxc1" causes the sign of TipDxc1 to be switched.
         OutListTmp          = OutListTmp(2:)

         Indx = IndexCharAry( OutListTmp(1:OutStrLenM1), ValidParamAry )
      END IF


      IF ( Indx > 0 ) THEN ! we found the channel name
         p%OutParam(I)%Indx     = ParamIndxAry(Indx)
         IF ( InvalidOutput( ParamIndxAry(Indx) ) ) THEN  ! but, it isn't valid for these settings
            p%OutParam(I)%Units = "INVALID"
            p%OutParam(I)%SignM = 0
         ELSE
            p%OutParam(I)%Units = ParamUnitsAry(Indx) ! it's a valid output
         END IF
      ELSE ! this channel isn't valid
         p%OutParam(I)%Indx  = Time                 ! pick any valid channel (I just picked "Time" here because it's universal)
         p%OutParam(I)%Units = "INVALID"
         p%OutParam(I)%SignM = 0                    ! multiply all results by zero

         CALL SetErrStat(ErrID_Fatal, TRIM(p%OutParam(I)%Name)//" is not an available output channel.",ErrStat,ErrMsg,RoutineName)
      END IF

   END DO

   RETURN
END SUBROUTINE SetOutParam
!----------------------------------------------------------------------------------------------------------------------------------
!End of code generated by Matlab script
!**********************************************************************************************************************************
