! ===================================================================================================
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these 
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary. 
! ===================================================================================================
! This code was generated by Write_ChckOutLst.m at 02-Mar-2015 10:37:31.


     ! Parameters related to output length (number of characters allowed in the output data headers):

   INTEGER(IntKi), PARAMETER      :: OutStrLenM1 = ChanLen - 1


     ! Indices for computing output channels:
     ! NOTES: 
     !    (1) These parameters are in the order stored in "OutListParameters.xlsx"
     !    (2) Array y%AllOuts() must be dimensioned to the value of the largest output parameter

     !  Time: 

   INTEGER(IntKi), PARAMETER      :: Time      =   0


     ! Blade 1 Tip Motions:

   INTEGER(IntKi), PARAMETER      :: TipDxc1   =   1
   INTEGER(IntKi), PARAMETER      :: TipDyc1   =   2
   INTEGER(IntKi), PARAMETER      :: TipDzc1   =   3
   INTEGER(IntKi), PARAMETER      :: TipDxb1   =   4
   INTEGER(IntKi), PARAMETER      :: TipDyb1   =   5
   INTEGER(IntKi), PARAMETER      :: TipALxb1  =   6
   INTEGER(IntKi), PARAMETER      :: TipALyb1  =   7
   INTEGER(IntKi), PARAMETER      :: TipALzb1  =   8
   INTEGER(IntKi), PARAMETER      :: TipRDxb1  =   9
   INTEGER(IntKi), PARAMETER      :: TipRDyb1  =  10
   INTEGER(IntKi), PARAMETER      :: TipRDzc1  =  11
   INTEGER(IntKi), PARAMETER      :: TipClrnc1 =  12


     ! Blade 2 Tip Motions:

   INTEGER(IntKi), PARAMETER      :: TipDxc2   =  13
   INTEGER(IntKi), PARAMETER      :: TipDyc2   =  14
   INTEGER(IntKi), PARAMETER      :: TipDzc2   =  15
   INTEGER(IntKi), PARAMETER      :: TipDxb2   =  16
   INTEGER(IntKi), PARAMETER      :: TipDyb2   =  17
   INTEGER(IntKi), PARAMETER      :: TipALxb2  =  18
   INTEGER(IntKi), PARAMETER      :: TipALyb2  =  19
   INTEGER(IntKi), PARAMETER      :: TipALzb2  =  20
   INTEGER(IntKi), PARAMETER      :: TipRDxb2  =  21
   INTEGER(IntKi), PARAMETER      :: TipRDyb2  =  22
   INTEGER(IntKi), PARAMETER      :: TipRDzc2  =  23
   INTEGER(IntKi), PARAMETER      :: TipClrnc2 =  24


     ! Blade 3 Tip Motions:

   INTEGER(IntKi), PARAMETER      :: TipDxc3   =  25
   INTEGER(IntKi), PARAMETER      :: TipDyc3   =  26
   INTEGER(IntKi), PARAMETER      :: TipDzc3   =  27
   INTEGER(IntKi), PARAMETER      :: TipDxb3   =  28
   INTEGER(IntKi), PARAMETER      :: TipDyb3   =  29
   INTEGER(IntKi), PARAMETER      :: TipALxb3  =  30
   INTEGER(IntKi), PARAMETER      :: TipALyb3  =  31
   INTEGER(IntKi), PARAMETER      :: TipALzb3  =  32
   INTEGER(IntKi), PARAMETER      :: TipRDxb3  =  33
   INTEGER(IntKi), PARAMETER      :: TipRDyb3  =  34
   INTEGER(IntKi), PARAMETER      :: TipRDzc3  =  35
   INTEGER(IntKi), PARAMETER      :: TipClrnc3 =  36


     ! Blade 1 Local Span Motions:

   INTEGER(IntKi), PARAMETER      :: Spn1ALxb1 =  37
   INTEGER(IntKi), PARAMETER      :: Spn1ALyb1 =  38
   INTEGER(IntKi), PARAMETER      :: Spn1ALzb1 =  39
   INTEGER(IntKi), PARAMETER      :: Spn2ALxb1 =  40
   INTEGER(IntKi), PARAMETER      :: Spn2ALyb1 =  41
   INTEGER(IntKi), PARAMETER      :: Spn2ALzb1 =  42
   INTEGER(IntKi), PARAMETER      :: Spn3ALxb1 =  43
   INTEGER(IntKi), PARAMETER      :: Spn3ALyb1 =  44
   INTEGER(IntKi), PARAMETER      :: Spn3ALzb1 =  45
   INTEGER(IntKi), PARAMETER      :: Spn4ALxb1 =  46
   INTEGER(IntKi), PARAMETER      :: Spn4ALyb1 =  47
   INTEGER(IntKi), PARAMETER      :: Spn4ALzb1 =  48
   INTEGER(IntKi), PARAMETER      :: Spn5ALxb1 =  49
   INTEGER(IntKi), PARAMETER      :: Spn5ALyb1 =  50
   INTEGER(IntKi), PARAMETER      :: Spn5ALzb1 =  51
   INTEGER(IntKi), PARAMETER      :: Spn6ALxb1 =  52
   INTEGER(IntKi), PARAMETER      :: Spn6ALyb1 =  53
   INTEGER(IntKi), PARAMETER      :: Spn6ALzb1 =  54
   INTEGER(IntKi), PARAMETER      :: Spn7ALxb1 =  55
   INTEGER(IntKi), PARAMETER      :: Spn7ALyb1 =  56
   INTEGER(IntKi), PARAMETER      :: Spn7ALzb1 =  57
   INTEGER(IntKi), PARAMETER      :: Spn8ALxb1 =  58
   INTEGER(IntKi), PARAMETER      :: Spn8ALyb1 =  59
   INTEGER(IntKi), PARAMETER      :: Spn8ALzb1 =  60
   INTEGER(IntKi), PARAMETER      :: Spn9ALxb1 =  61
   INTEGER(IntKi), PARAMETER      :: Spn9ALyb1 =  62
   INTEGER(IntKi), PARAMETER      :: Spn9ALzb1 =  63
   INTEGER(IntKi), PARAMETER      :: Spn1TDxb1 =  64
   INTEGER(IntKi), PARAMETER      :: Spn1TDyb1 =  65
   INTEGER(IntKi), PARAMETER      :: Spn1TDzb1 =  66
   INTEGER(IntKi), PARAMETER      :: Spn2TDxb1 =  67
   INTEGER(IntKi), PARAMETER      :: Spn2TDyb1 =  68
   INTEGER(IntKi), PARAMETER      :: Spn2TDzb1 =  69
   INTEGER(IntKi), PARAMETER      :: Spn3TDxb1 =  70
   INTEGER(IntKi), PARAMETER      :: Spn3TDyb1 =  71
   INTEGER(IntKi), PARAMETER      :: Spn3TDzb1 =  72
   INTEGER(IntKi), PARAMETER      :: Spn4TDxb1 =  73
   INTEGER(IntKi), PARAMETER      :: Spn4TDyb1 =  74
   INTEGER(IntKi), PARAMETER      :: Spn4TDzb1 =  75
   INTEGER(IntKi), PARAMETER      :: Spn5TDxb1 =  76
   INTEGER(IntKi), PARAMETER      :: Spn5TDyb1 =  77
   INTEGER(IntKi), PARAMETER      :: Spn5TDzb1 =  78
   INTEGER(IntKi), PARAMETER      :: Spn6TDxb1 =  79
   INTEGER(IntKi), PARAMETER      :: Spn6TDyb1 =  80
   INTEGER(IntKi), PARAMETER      :: Spn6TDzb1 =  81
   INTEGER(IntKi), PARAMETER      :: Spn7TDxb1 =  82
   INTEGER(IntKi), PARAMETER      :: Spn7TDyb1 =  83
   INTEGER(IntKi), PARAMETER      :: Spn7TDzb1 =  84
   INTEGER(IntKi), PARAMETER      :: Spn8TDxb1 =  85
   INTEGER(IntKi), PARAMETER      :: Spn8TDyb1 =  86
   INTEGER(IntKi), PARAMETER      :: Spn8TDzb1 =  87
   INTEGER(IntKi), PARAMETER      :: Spn9TDxb1 =  88
   INTEGER(IntKi), PARAMETER      :: Spn9TDyb1 =  89
   INTEGER(IntKi), PARAMETER      :: Spn9TDzb1 =  90
   INTEGER(IntKi), PARAMETER      :: Spn1RDxb1 =  91
   INTEGER(IntKi), PARAMETER      :: Spn1RDyb1 =  92
   INTEGER(IntKi), PARAMETER      :: Spn1RDzb1 =  93
   INTEGER(IntKi), PARAMETER      :: Spn2RDxb1 =  94
   INTEGER(IntKi), PARAMETER      :: Spn2RDyb1 =  95
   INTEGER(IntKi), PARAMETER      :: Spn2RDzb1 =  96
   INTEGER(IntKi), PARAMETER      :: Spn3RDxb1 =  97
   INTEGER(IntKi), PARAMETER      :: Spn3RDyb1 =  98
   INTEGER(IntKi), PARAMETER      :: Spn3RDzb1 =  99
   INTEGER(IntKi), PARAMETER      :: Spn4RDxb1 = 100
   INTEGER(IntKi), PARAMETER      :: Spn4RDyb1 = 101
   INTEGER(IntKi), PARAMETER      :: Spn4RDzb1 = 102
   INTEGER(IntKi), PARAMETER      :: Spn5RDxb1 = 103
   INTEGER(IntKi), PARAMETER      :: Spn5RDyb1 = 104
   INTEGER(IntKi), PARAMETER      :: Spn5RDzb1 = 105
   INTEGER(IntKi), PARAMETER      :: Spn6RDxb1 = 106
   INTEGER(IntKi), PARAMETER      :: Spn6RDyb1 = 107
   INTEGER(IntKi), PARAMETER      :: Spn6RDzb1 = 108
   INTEGER(IntKi), PARAMETER      :: Spn7RDxb1 = 109
   INTEGER(IntKi), PARAMETER      :: Spn7RDyb1 = 110
   INTEGER(IntKi), PARAMETER      :: Spn7RDzb1 = 111
   INTEGER(IntKi), PARAMETER      :: Spn8RDxb1 = 112
   INTEGER(IntKi), PARAMETER      :: Spn8RDyb1 = 113
   INTEGER(IntKi), PARAMETER      :: Spn8RDzb1 = 114
   INTEGER(IntKi), PARAMETER      :: Spn9RDxb1 = 115
   INTEGER(IntKi), PARAMETER      :: Spn9RDyb1 = 116
   INTEGER(IntKi), PARAMETER      :: Spn9RDzb1 = 117


     ! Blade 2 Local Span Motions:

   INTEGER(IntKi), PARAMETER      :: Spn1ALxb2 = 118
   INTEGER(IntKi), PARAMETER      :: Spn1ALyb2 = 119
   INTEGER(IntKi), PARAMETER      :: Spn1ALzb2 = 120
   INTEGER(IntKi), PARAMETER      :: Spn2ALxb2 = 121
   INTEGER(IntKi), PARAMETER      :: Spn2ALyb2 = 122
   INTEGER(IntKi), PARAMETER      :: Spn2ALzb2 = 123
   INTEGER(IntKi), PARAMETER      :: Spn3ALxb2 = 124
   INTEGER(IntKi), PARAMETER      :: Spn3ALyb2 = 125
   INTEGER(IntKi), PARAMETER      :: Spn3ALzb2 = 126
   INTEGER(IntKi), PARAMETER      :: Spn4ALxb2 = 127
   INTEGER(IntKi), PARAMETER      :: Spn4ALyb2 = 128
   INTEGER(IntKi), PARAMETER      :: Spn4ALzb2 = 129
   INTEGER(IntKi), PARAMETER      :: Spn5ALxb2 = 130
   INTEGER(IntKi), PARAMETER      :: Spn5ALyb2 = 131
   INTEGER(IntKi), PARAMETER      :: Spn5ALzb2 = 132
   INTEGER(IntKi), PARAMETER      :: Spn6ALxb2 = 133
   INTEGER(IntKi), PARAMETER      :: Spn6ALyb2 = 134
   INTEGER(IntKi), PARAMETER      :: Spn6ALzb2 = 135
   INTEGER(IntKi), PARAMETER      :: Spn7ALxb2 = 136
   INTEGER(IntKi), PARAMETER      :: Spn7ALyb2 = 137
   INTEGER(IntKi), PARAMETER      :: Spn7ALzb2 = 138
   INTEGER(IntKi), PARAMETER      :: Spn8ALxb2 = 139
   INTEGER(IntKi), PARAMETER      :: Spn8ALyb2 = 140
   INTEGER(IntKi), PARAMETER      :: Spn8ALzb2 = 141
   INTEGER(IntKi), PARAMETER      :: Spn9ALxb2 = 142
   INTEGER(IntKi), PARAMETER      :: Spn9ALyb2 = 143
   INTEGER(IntKi), PARAMETER      :: Spn9ALzb2 = 144
   INTEGER(IntKi), PARAMETER      :: Spn1TDxb2 = 145
   INTEGER(IntKi), PARAMETER      :: Spn1TDyb2 = 146
   INTEGER(IntKi), PARAMETER      :: Spn1TDzb2 = 147
   INTEGER(IntKi), PARAMETER      :: Spn2TDxb2 = 148
   INTEGER(IntKi), PARAMETER      :: Spn2TDyb2 = 149
   INTEGER(IntKi), PARAMETER      :: Spn2TDzb2 = 150
   INTEGER(IntKi), PARAMETER      :: Spn3TDxb2 = 151
   INTEGER(IntKi), PARAMETER      :: Spn3TDyb2 = 152
   INTEGER(IntKi), PARAMETER      :: Spn3TDzb2 = 153
   INTEGER(IntKi), PARAMETER      :: Spn4TDxb2 = 154
   INTEGER(IntKi), PARAMETER      :: Spn4TDyb2 = 155
   INTEGER(IntKi), PARAMETER      :: Spn4TDzb2 = 156
   INTEGER(IntKi), PARAMETER      :: Spn5TDxb2 = 157
   INTEGER(IntKi), PARAMETER      :: Spn5TDyb2 = 158
   INTEGER(IntKi), PARAMETER      :: Spn5TDzb2 = 159
   INTEGER(IntKi), PARAMETER      :: Spn6TDxb2 = 160
   INTEGER(IntKi), PARAMETER      :: Spn6TDyb2 = 161
   INTEGER(IntKi), PARAMETER      :: Spn6TDzb2 = 162
   INTEGER(IntKi), PARAMETER      :: Spn7TDxb2 = 163
   INTEGER(IntKi), PARAMETER      :: Spn7TDyb2 = 164
   INTEGER(IntKi), PARAMETER      :: Spn7TDzb2 = 165
   INTEGER(IntKi), PARAMETER      :: Spn8TDxb2 = 166
   INTEGER(IntKi), PARAMETER      :: Spn8TDyb2 = 167
   INTEGER(IntKi), PARAMETER      :: Spn8TDzb2 = 168
   INTEGER(IntKi), PARAMETER      :: Spn9TDxb2 = 169
   INTEGER(IntKi), PARAMETER      :: Spn9TDyb2 = 170
   INTEGER(IntKi), PARAMETER      :: Spn9TDzb2 = 171
   INTEGER(IntKi), PARAMETER      :: Spn1RDxb2 = 172
   INTEGER(IntKi), PARAMETER      :: Spn1RDyb2 = 173
   INTEGER(IntKi), PARAMETER      :: Spn1RDzb2 = 174
   INTEGER(IntKi), PARAMETER      :: Spn2RDxb2 = 175
   INTEGER(IntKi), PARAMETER      :: Spn2RDyb2 = 176
   INTEGER(IntKi), PARAMETER      :: Spn2RDzb2 = 177
   INTEGER(IntKi), PARAMETER      :: Spn3RDxb2 = 178
   INTEGER(IntKi), PARAMETER      :: Spn3RDyb2 = 179
   INTEGER(IntKi), PARAMETER      :: Spn3RDzb2 = 180
   INTEGER(IntKi), PARAMETER      :: Spn4RDxb2 = 181
   INTEGER(IntKi), PARAMETER      :: Spn4RDyb2 = 182
   INTEGER(IntKi), PARAMETER      :: Spn4RDzb2 = 183
   INTEGER(IntKi), PARAMETER      :: Spn5RDxb2 = 184
   INTEGER(IntKi), PARAMETER      :: Spn5RDyb2 = 185
   INTEGER(IntKi), PARAMETER      :: Spn5RDzb2 = 186
   INTEGER(IntKi), PARAMETER      :: Spn6RDxb2 = 187
   INTEGER(IntKi), PARAMETER      :: Spn6RDyb2 = 188
   INTEGER(IntKi), PARAMETER      :: Spn6RDzb2 = 189
   INTEGER(IntKi), PARAMETER      :: Spn7RDxb2 = 190
   INTEGER(IntKi), PARAMETER      :: Spn7RDyb2 = 191
   INTEGER(IntKi), PARAMETER      :: Spn7RDzb2 = 192
   INTEGER(IntKi), PARAMETER      :: Spn8RDxb2 = 193
   INTEGER(IntKi), PARAMETER      :: Spn8RDyb2 = 194
   INTEGER(IntKi), PARAMETER      :: Spn8RDzb2 = 195
   INTEGER(IntKi), PARAMETER      :: Spn9RDxb2 = 196
   INTEGER(IntKi), PARAMETER      :: Spn9RDyb2 = 197
   INTEGER(IntKi), PARAMETER      :: Spn9RDzb2 = 198


     ! Blade 3 Local Span Motions:

   INTEGER(IntKi), PARAMETER      :: Spn1ALxb3 = 199
   INTEGER(IntKi), PARAMETER      :: Spn1ALyb3 = 200
   INTEGER(IntKi), PARAMETER      :: Spn1ALzb3 = 201
   INTEGER(IntKi), PARAMETER      :: Spn2ALxb3 = 202
   INTEGER(IntKi), PARAMETER      :: Spn2ALyb3 = 203
   INTEGER(IntKi), PARAMETER      :: Spn2ALzb3 = 204
   INTEGER(IntKi), PARAMETER      :: Spn3ALxb3 = 205
   INTEGER(IntKi), PARAMETER      :: Spn3ALyb3 = 206
   INTEGER(IntKi), PARAMETER      :: Spn3ALzb3 = 207
   INTEGER(IntKi), PARAMETER      :: Spn4ALxb3 = 208
   INTEGER(IntKi), PARAMETER      :: Spn4ALyb3 = 209
   INTEGER(IntKi), PARAMETER      :: Spn4ALzb3 = 210
   INTEGER(IntKi), PARAMETER      :: Spn5ALxb3 = 211
   INTEGER(IntKi), PARAMETER      :: Spn5ALyb3 = 212
   INTEGER(IntKi), PARAMETER      :: Spn5ALzb3 = 213
   INTEGER(IntKi), PARAMETER      :: Spn6ALxb3 = 214
   INTEGER(IntKi), PARAMETER      :: Spn6ALyb3 = 215
   INTEGER(IntKi), PARAMETER      :: Spn6ALzb3 = 216
   INTEGER(IntKi), PARAMETER      :: Spn7ALxb3 = 217
   INTEGER(IntKi), PARAMETER      :: Spn7ALyb3 = 218
   INTEGER(IntKi), PARAMETER      :: Spn7ALzb3 = 219
   INTEGER(IntKi), PARAMETER      :: Spn8ALxb3 = 220
   INTEGER(IntKi), PARAMETER      :: Spn8ALyb3 = 221
   INTEGER(IntKi), PARAMETER      :: Spn8ALzb3 = 222
   INTEGER(IntKi), PARAMETER      :: Spn9ALxb3 = 223
   INTEGER(IntKi), PARAMETER      :: Spn9ALyb3 = 224
   INTEGER(IntKi), PARAMETER      :: Spn9ALzb3 = 225
   INTEGER(IntKi), PARAMETER      :: Spn1TDxb3 = 226
   INTEGER(IntKi), PARAMETER      :: Spn1TDyb3 = 227
   INTEGER(IntKi), PARAMETER      :: Spn1TDzb3 = 228
   INTEGER(IntKi), PARAMETER      :: Spn2TDxb3 = 229
   INTEGER(IntKi), PARAMETER      :: Spn2TDyb3 = 230
   INTEGER(IntKi), PARAMETER      :: Spn2TDzb3 = 231
   INTEGER(IntKi), PARAMETER      :: Spn3TDxb3 = 232
   INTEGER(IntKi), PARAMETER      :: Spn3TDyb3 = 233
   INTEGER(IntKi), PARAMETER      :: Spn3TDzb3 = 234
   INTEGER(IntKi), PARAMETER      :: Spn4TDxb3 = 235
   INTEGER(IntKi), PARAMETER      :: Spn4TDyb3 = 236
   INTEGER(IntKi), PARAMETER      :: Spn4TDzb3 = 237
   INTEGER(IntKi), PARAMETER      :: Spn5TDxb3 = 238
   INTEGER(IntKi), PARAMETER      :: Spn5TDyb3 = 239
   INTEGER(IntKi), PARAMETER      :: Spn5TDzb3 = 240
   INTEGER(IntKi), PARAMETER      :: Spn6TDxb3 = 241
   INTEGER(IntKi), PARAMETER      :: Spn6TDyb3 = 242
   INTEGER(IntKi), PARAMETER      :: Spn6TDzb3 = 243
   INTEGER(IntKi), PARAMETER      :: Spn7TDxb3 = 244
   INTEGER(IntKi), PARAMETER      :: Spn7TDyb3 = 245
   INTEGER(IntKi), PARAMETER      :: Spn7TDzb3 = 246
   INTEGER(IntKi), PARAMETER      :: Spn8TDxb3 = 247
   INTEGER(IntKi), PARAMETER      :: Spn8TDyb3 = 248
   INTEGER(IntKi), PARAMETER      :: Spn8TDzb3 = 249
   INTEGER(IntKi), PARAMETER      :: Spn9TDxb3 = 250
   INTEGER(IntKi), PARAMETER      :: Spn9TDyb3 = 251
   INTEGER(IntKi), PARAMETER      :: Spn9TDzb3 = 252
   INTEGER(IntKi), PARAMETER      :: Spn1RDxb3 = 253
   INTEGER(IntKi), PARAMETER      :: Spn1RDyb3 = 254
   INTEGER(IntKi), PARAMETER      :: Spn1RDzb3 = 255
   INTEGER(IntKi), PARAMETER      :: Spn2RDxb3 = 256
   INTEGER(IntKi), PARAMETER      :: Spn2RDyb3 = 257
   INTEGER(IntKi), PARAMETER      :: Spn2RDzb3 = 258
   INTEGER(IntKi), PARAMETER      :: Spn3RDxb3 = 259
   INTEGER(IntKi), PARAMETER      :: Spn3RDyb3 = 260
   INTEGER(IntKi), PARAMETER      :: Spn3RDzb3 = 261
   INTEGER(IntKi), PARAMETER      :: Spn4RDxb3 = 262
   INTEGER(IntKi), PARAMETER      :: Spn4RDyb3 = 263
   INTEGER(IntKi), PARAMETER      :: Spn4RDzb3 = 264
   INTEGER(IntKi), PARAMETER      :: Spn5RDxb3 = 265
   INTEGER(IntKi), PARAMETER      :: Spn5RDyb3 = 266
   INTEGER(IntKi), PARAMETER      :: Spn5RDzb3 = 267
   INTEGER(IntKi), PARAMETER      :: Spn6RDxb3 = 268
   INTEGER(IntKi), PARAMETER      :: Spn6RDyb3 = 269
   INTEGER(IntKi), PARAMETER      :: Spn6RDzb3 = 270
   INTEGER(IntKi), PARAMETER      :: Spn7RDxb3 = 271
   INTEGER(IntKi), PARAMETER      :: Spn7RDyb3 = 272
   INTEGER(IntKi), PARAMETER      :: Spn7RDzb3 = 273
   INTEGER(IntKi), PARAMETER      :: Spn8RDxb3 = 274
   INTEGER(IntKi), PARAMETER      :: Spn8RDyb3 = 275
   INTEGER(IntKi), PARAMETER      :: Spn8RDzb3 = 276
   INTEGER(IntKi), PARAMETER      :: Spn9RDxb3 = 277
   INTEGER(IntKi), PARAMETER      :: Spn9RDyb3 = 278
   INTEGER(IntKi), PARAMETER      :: Spn9RDzb3 = 279


     ! Blade Pitch Motions:

   INTEGER(IntKi), PARAMETER      :: PtchPMzc1 = 280
   INTEGER(IntKi), PARAMETER      :: PtchPMzc2 = 281
   INTEGER(IntKi), PARAMETER      :: PtchPMzc3 = 282


     ! Teeter Motions:

   INTEGER(IntKi), PARAMETER      :: TeetPya   = 283
   INTEGER(IntKi), PARAMETER      :: TeetVya   = 284
   INTEGER(IntKi), PARAMETER      :: TeetAya   = 285


     ! Shaft Motions:

   INTEGER(IntKi), PARAMETER      :: LSSTipPxa = 286
   INTEGER(IntKi), PARAMETER      :: LSSTipVxa = 287
   INTEGER(IntKi), PARAMETER      :: LSSTipAxa = 288
   INTEGER(IntKi), PARAMETER      :: LSSGagPxa = 289
   INTEGER(IntKi), PARAMETER      :: LSSGagVxa = 290
   INTEGER(IntKi), PARAMETER      :: LSSGagAxa = 291
   INTEGER(IntKi), PARAMETER      :: HSShftV   = 292
   INTEGER(IntKi), PARAMETER      :: HSShftA   = 293


     ! Nacelle IMU Motions:

   INTEGER(IntKi), PARAMETER      :: NcIMUTVxs = 294
   INTEGER(IntKi), PARAMETER      :: NcIMUTVys = 295
   INTEGER(IntKi), PARAMETER      :: NcIMUTVzs = 296
   INTEGER(IntKi), PARAMETER      :: NcIMUTAxs = 297
   INTEGER(IntKi), PARAMETER      :: NcIMUTAys = 298
   INTEGER(IntKi), PARAMETER      :: NcIMUTAzs = 299
   INTEGER(IntKi), PARAMETER      :: NcIMURVxs = 300
   INTEGER(IntKi), PARAMETER      :: NcIMURVys = 301
   INTEGER(IntKi), PARAMETER      :: NcIMURVzs = 302
   INTEGER(IntKi), PARAMETER      :: NcIMURAxs = 303
   INTEGER(IntKi), PARAMETER      :: NcIMURAys = 304
   INTEGER(IntKi), PARAMETER      :: NcIMURAzs = 305


     ! Rotor-Furl Motions:

   INTEGER(IntKi), PARAMETER      :: RotFurlP  = 306
   INTEGER(IntKi), PARAMETER      :: RotFurlV  = 307
   INTEGER(IntKi), PARAMETER      :: RotFurlA  = 308


     ! Tail-Furl Motions:

   INTEGER(IntKi), PARAMETER      :: TailFurlP = 309
   INTEGER(IntKi), PARAMETER      :: TailFurlV = 310
   INTEGER(IntKi), PARAMETER      :: TailFurlA = 311


     ! Nacelle Yaw Motions:

   INTEGER(IntKi), PARAMETER      :: YawPzn    = 312
   INTEGER(IntKi), PARAMETER      :: YawVzn    = 313
   INTEGER(IntKi), PARAMETER      :: YawAzn    = 314


     ! Tower-Top / Yaw Bearing Motions:

   INTEGER(IntKi), PARAMETER      :: YawBrTDxp = 315
   INTEGER(IntKi), PARAMETER      :: YawBrTDyp = 316
   INTEGER(IntKi), PARAMETER      :: YawBrTDzp = 317
   INTEGER(IntKi), PARAMETER      :: YawBrTDxt = 318
   INTEGER(IntKi), PARAMETER      :: YawBrTDyt = 319
   INTEGER(IntKi), PARAMETER      :: YawBrTDzt = 320
   INTEGER(IntKi), PARAMETER      :: YawBrTAxp = 321
   INTEGER(IntKi), PARAMETER      :: YawBrTAyp = 322
   INTEGER(IntKi), PARAMETER      :: YawBrTAzp = 323
   INTEGER(IntKi), PARAMETER      :: YawBrRDxt = 324
   INTEGER(IntKi), PARAMETER      :: YawBrRDyt = 325
   INTEGER(IntKi), PARAMETER      :: YawBrRDzt = 326
   INTEGER(IntKi), PARAMETER      :: YawBrRVxp = 327
   INTEGER(IntKi), PARAMETER      :: YawBrRVyp = 328
   INTEGER(IntKi), PARAMETER      :: YawBrRVzp = 329
   INTEGER(IntKi), PARAMETER      :: YawBrRAxp = 330
   INTEGER(IntKi), PARAMETER      :: YawBrRAyp = 331
   INTEGER(IntKi), PARAMETER      :: YawBrRAzp = 332


     ! Local Tower Motions:

   INTEGER(IntKi), PARAMETER      :: TwHt1ALxt = 333
   INTEGER(IntKi), PARAMETER      :: TwHt1ALyt = 334
   INTEGER(IntKi), PARAMETER      :: TwHt1ALzt = 335
   INTEGER(IntKi), PARAMETER      :: TwHt2ALxt = 336
   INTEGER(IntKi), PARAMETER      :: TwHt2ALyt = 337
   INTEGER(IntKi), PARAMETER      :: TwHt2ALzt = 338
   INTEGER(IntKi), PARAMETER      :: TwHt3ALxt = 339
   INTEGER(IntKi), PARAMETER      :: TwHt3ALyt = 340
   INTEGER(IntKi), PARAMETER      :: TwHt3ALzt = 341
   INTEGER(IntKi), PARAMETER      :: TwHt4ALxt = 342
   INTEGER(IntKi), PARAMETER      :: TwHt4ALyt = 343
   INTEGER(IntKi), PARAMETER      :: TwHt4ALzt = 344
   INTEGER(IntKi), PARAMETER      :: TwHt5ALxt = 345
   INTEGER(IntKi), PARAMETER      :: TwHt5ALyt = 346
   INTEGER(IntKi), PARAMETER      :: TwHt5ALzt = 347
   INTEGER(IntKi), PARAMETER      :: TwHt6ALxt = 348
   INTEGER(IntKi), PARAMETER      :: TwHt6ALyt = 349
   INTEGER(IntKi), PARAMETER      :: TwHt6ALzt = 350
   INTEGER(IntKi), PARAMETER      :: TwHt7ALxt = 351
   INTEGER(IntKi), PARAMETER      :: TwHt7ALyt = 352
   INTEGER(IntKi), PARAMETER      :: TwHt7ALzt = 353
   INTEGER(IntKi), PARAMETER      :: TwHt8ALxt = 354
   INTEGER(IntKi), PARAMETER      :: TwHt8ALyt = 355
   INTEGER(IntKi), PARAMETER      :: TwHt8ALzt = 356
   INTEGER(IntKi), PARAMETER      :: TwHt9ALxt = 357
   INTEGER(IntKi), PARAMETER      :: TwHt9ALyt = 358
   INTEGER(IntKi), PARAMETER      :: TwHt9ALzt = 359
   INTEGER(IntKi), PARAMETER      :: TwHt1TDxt = 360
   INTEGER(IntKi), PARAMETER      :: TwHt1TDyt = 361
   INTEGER(IntKi), PARAMETER      :: TwHt1TDzt = 362
   INTEGER(IntKi), PARAMETER      :: TwHt2TDxt = 363
   INTEGER(IntKi), PARAMETER      :: TwHt2TDyt = 364
   INTEGER(IntKi), PARAMETER      :: TwHt2TDzt = 365
   INTEGER(IntKi), PARAMETER      :: TwHt3TDxt = 366
   INTEGER(IntKi), PARAMETER      :: TwHt3TDyt = 367
   INTEGER(IntKi), PARAMETER      :: TwHt3TDzt = 368
   INTEGER(IntKi), PARAMETER      :: TwHt4TDxt = 369
   INTEGER(IntKi), PARAMETER      :: TwHt4TDyt = 370
   INTEGER(IntKi), PARAMETER      :: TwHt4TDzt = 371
   INTEGER(IntKi), PARAMETER      :: TwHt5TDxt = 372
   INTEGER(IntKi), PARAMETER      :: TwHt5TDyt = 373
   INTEGER(IntKi), PARAMETER      :: TwHt5TDzt = 374
   INTEGER(IntKi), PARAMETER      :: TwHt6TDxt = 375
   INTEGER(IntKi), PARAMETER      :: TwHt6TDyt = 376
   INTEGER(IntKi), PARAMETER      :: TwHt6TDzt = 377
   INTEGER(IntKi), PARAMETER      :: TwHt7TDxt = 378
   INTEGER(IntKi), PARAMETER      :: TwHt7TDyt = 379
   INTEGER(IntKi), PARAMETER      :: TwHt7TDzt = 380
   INTEGER(IntKi), PARAMETER      :: TwHt8TDxt = 381
   INTEGER(IntKi), PARAMETER      :: TwHt8TDyt = 382
   INTEGER(IntKi), PARAMETER      :: TwHt8TDzt = 383
   INTEGER(IntKi), PARAMETER      :: TwHt9TDxt = 384
   INTEGER(IntKi), PARAMETER      :: TwHt9TDyt = 385
   INTEGER(IntKi), PARAMETER      :: TwHt9TDzt = 386
   INTEGER(IntKi), PARAMETER      :: TwHt1RDxt = 387
   INTEGER(IntKi), PARAMETER      :: TwHt1RDyt = 388
   INTEGER(IntKi), PARAMETER      :: TwHt1RDzt = 389
   INTEGER(IntKi), PARAMETER      :: TwHt2RDxt = 390
   INTEGER(IntKi), PARAMETER      :: TwHt2RDyt = 391
   INTEGER(IntKi), PARAMETER      :: TwHt2RDzt = 392
   INTEGER(IntKi), PARAMETER      :: TwHt3RDxt = 393
   INTEGER(IntKi), PARAMETER      :: TwHt3RDyt = 394
   INTEGER(IntKi), PARAMETER      :: TwHt3RDzt = 395
   INTEGER(IntKi), PARAMETER      :: TwHt4RDxt = 396
   INTEGER(IntKi), PARAMETER      :: TwHt4RDyt = 397
   INTEGER(IntKi), PARAMETER      :: TwHt4RDzt = 398
   INTEGER(IntKi), PARAMETER      :: TwHt5RDxt = 399
   INTEGER(IntKi), PARAMETER      :: TwHt5RDyt = 400
   INTEGER(IntKi), PARAMETER      :: TwHt5RDzt = 401
   INTEGER(IntKi), PARAMETER      :: TwHt6RDxt = 402
   INTEGER(IntKi), PARAMETER      :: TwHt6RDyt = 403
   INTEGER(IntKi), PARAMETER      :: TwHt6RDzt = 404
   INTEGER(IntKi), PARAMETER      :: TwHt7RDxt = 405
   INTEGER(IntKi), PARAMETER      :: TwHt7RDyt = 406
   INTEGER(IntKi), PARAMETER      :: TwHt7RDzt = 407
   INTEGER(IntKi), PARAMETER      :: TwHt8RDxt = 408
   INTEGER(IntKi), PARAMETER      :: TwHt8RDyt = 409
   INTEGER(IntKi), PARAMETER      :: TwHt8RDzt = 410
   INTEGER(IntKi), PARAMETER      :: TwHt9RDxt = 411
   INTEGER(IntKi), PARAMETER      :: TwHt9RDyt = 412
   INTEGER(IntKi), PARAMETER      :: TwHt9RDzt = 413
   INTEGER(IntKi), PARAMETER      :: TwHt1TPxi = 414
   INTEGER(IntKi), PARAMETER      :: TwHt1TPyi = 415
   INTEGER(IntKi), PARAMETER      :: TwHt1TPzi = 416
   INTEGER(IntKi), PARAMETER      :: TwHt2TPxi = 417
   INTEGER(IntKi), PARAMETER      :: TwHt2TPyi = 418
   INTEGER(IntKi), PARAMETER      :: TwHt2TPzi = 419
   INTEGER(IntKi), PARAMETER      :: TwHt3TPxi = 420
   INTEGER(IntKi), PARAMETER      :: TwHt3TPyi = 421
   INTEGER(IntKi), PARAMETER      :: TwHt3TPzi = 422
   INTEGER(IntKi), PARAMETER      :: TwHt4TPxi = 423
   INTEGER(IntKi), PARAMETER      :: TwHt4TPyi = 424
   INTEGER(IntKi), PARAMETER      :: TwHt4TPzi = 425
   INTEGER(IntKi), PARAMETER      :: TwHt5TPxi = 426
   INTEGER(IntKi), PARAMETER      :: TwHt5TPyi = 427
   INTEGER(IntKi), PARAMETER      :: TwHt5TPzi = 428
   INTEGER(IntKi), PARAMETER      :: TwHt6TPxi = 429
   INTEGER(IntKi), PARAMETER      :: TwHt6TPyi = 430
   INTEGER(IntKi), PARAMETER      :: TwHt6TPzi = 431
   INTEGER(IntKi), PARAMETER      :: TwHt7TPxi = 432
   INTEGER(IntKi), PARAMETER      :: TwHt7TPyi = 433
   INTEGER(IntKi), PARAMETER      :: TwHt7TPzi = 434
   INTEGER(IntKi), PARAMETER      :: TwHt8TPxi = 435
   INTEGER(IntKi), PARAMETER      :: TwHt8TPyi = 436
   INTEGER(IntKi), PARAMETER      :: TwHt8TPzi = 437
   INTEGER(IntKi), PARAMETER      :: TwHt9TPxi = 438
   INTEGER(IntKi), PARAMETER      :: TwHt9TPyi = 439
   INTEGER(IntKi), PARAMETER      :: TwHt9TPzi = 440
   INTEGER(IntKi), PARAMETER      :: TwHt1RPxi = 441
   INTEGER(IntKi), PARAMETER      :: TwHt1RPyi = 442
   INTEGER(IntKi), PARAMETER      :: TwHt1RPzi = 443
   INTEGER(IntKi), PARAMETER      :: TwHt2RPxi = 444
   INTEGER(IntKi), PARAMETER      :: TwHt2RPyi = 445
   INTEGER(IntKi), PARAMETER      :: TwHt2RPzi = 446
   INTEGER(IntKi), PARAMETER      :: TwHt3RPxi = 447
   INTEGER(IntKi), PARAMETER      :: TwHt3RPyi = 448
   INTEGER(IntKi), PARAMETER      :: TwHt3RPzi = 449
   INTEGER(IntKi), PARAMETER      :: TwHt4RPxi = 450
   INTEGER(IntKi), PARAMETER      :: TwHt4RPyi = 451
   INTEGER(IntKi), PARAMETER      :: TwHt4RPzi = 452
   INTEGER(IntKi), PARAMETER      :: TwHt5RPxi = 453
   INTEGER(IntKi), PARAMETER      :: TwHt5RPyi = 454
   INTEGER(IntKi), PARAMETER      :: TwHt5RPzi = 455
   INTEGER(IntKi), PARAMETER      :: TwHt6RPxi = 456
   INTEGER(IntKi), PARAMETER      :: TwHt6RPyi = 457
   INTEGER(IntKi), PARAMETER      :: TwHt6RPzi = 458
   INTEGER(IntKi), PARAMETER      :: TwHt7RPxi = 459
   INTEGER(IntKi), PARAMETER      :: TwHt7RPyi = 460
   INTEGER(IntKi), PARAMETER      :: TwHt7RPzi = 461
   INTEGER(IntKi), PARAMETER      :: TwHt8RPxi = 462
   INTEGER(IntKi), PARAMETER      :: TwHt8RPyi = 463
   INTEGER(IntKi), PARAMETER      :: TwHt8RPzi = 464
   INTEGER(IntKi), PARAMETER      :: TwHt9RPxi = 465
   INTEGER(IntKi), PARAMETER      :: TwHt9RPyi = 466
   INTEGER(IntKi), PARAMETER      :: TwHt9RPzi = 467


     ! Platform Motions:

   INTEGER(IntKi), PARAMETER      :: PtfmTDxt  = 468
   INTEGER(IntKi), PARAMETER      :: PtfmTDyt  = 469
   INTEGER(IntKi), PARAMETER      :: PtfmTDzt  = 470
   INTEGER(IntKi), PARAMETER      :: PtfmTDxi  = 471
   INTEGER(IntKi), PARAMETER      :: PtfmTDyi  = 472
   INTEGER(IntKi), PARAMETER      :: PtfmTDzi  = 473
   INTEGER(IntKi), PARAMETER      :: PtfmTVxt  = 474
   INTEGER(IntKi), PARAMETER      :: PtfmTVyt  = 475
   INTEGER(IntKi), PARAMETER      :: PtfmTVzt  = 476
   INTEGER(IntKi), PARAMETER      :: PtfmTVxi  = 477
   INTEGER(IntKi), PARAMETER      :: PtfmTVyi  = 478
   INTEGER(IntKi), PARAMETER      :: PtfmTVzi  = 479
   INTEGER(IntKi), PARAMETER      :: PtfmTAxt  = 480
   INTEGER(IntKi), PARAMETER      :: PtfmTAyt  = 481
   INTEGER(IntKi), PARAMETER      :: PtfmTAzt  = 482
   INTEGER(IntKi), PARAMETER      :: PtfmTAxi  = 483
   INTEGER(IntKi), PARAMETER      :: PtfmTAyi  = 484
   INTEGER(IntKi), PARAMETER      :: PtfmTAzi  = 485
   INTEGER(IntKi), PARAMETER      :: PtfmRDxi  = 486
   INTEGER(IntKi), PARAMETER      :: PtfmRDyi  = 487
   INTEGER(IntKi), PARAMETER      :: PtfmRDzi  = 488
   INTEGER(IntKi), PARAMETER      :: PtfmRVxt  = 489
   INTEGER(IntKi), PARAMETER      :: PtfmRVyt  = 490
   INTEGER(IntKi), PARAMETER      :: PtfmRVzt  = 491
   INTEGER(IntKi), PARAMETER      :: PtfmRVxi  = 492
   INTEGER(IntKi), PARAMETER      :: PtfmRVyi  = 493
   INTEGER(IntKi), PARAMETER      :: PtfmRVzi  = 494
   INTEGER(IntKi), PARAMETER      :: PtfmRAxt  = 495
   INTEGER(IntKi), PARAMETER      :: PtfmRAyt  = 496
   INTEGER(IntKi), PARAMETER      :: PtfmRAzt  = 497
   INTEGER(IntKi), PARAMETER      :: PtfmRAxi  = 498
   INTEGER(IntKi), PARAMETER      :: PtfmRAyi  = 499
   INTEGER(IntKi), PARAMETER      :: PtfmRAzi  = 500


     ! Blade 1 Root Loads:

   INTEGER(IntKi), PARAMETER      :: RootFxc1  = 501
   INTEGER(IntKi), PARAMETER      :: RootFyc1  = 502
   INTEGER(IntKi), PARAMETER      :: RootFzc1  = 503
   INTEGER(IntKi), PARAMETER      :: RootFxb1  = 504
   INTEGER(IntKi), PARAMETER      :: RootFyb1  = 505
   INTEGER(IntKi), PARAMETER      :: RootMxc1  = 506
   INTEGER(IntKi), PARAMETER      :: RootMyc1  = 507
   INTEGER(IntKi), PARAMETER      :: RootMzc1  = 508
   INTEGER(IntKi), PARAMETER      :: RootMxb1  = 509
   INTEGER(IntKi), PARAMETER      :: RootMyb1  = 510


     ! Blade 2 Root Loads:

   INTEGER(IntKi), PARAMETER      :: RootFxc2  = 511
   INTEGER(IntKi), PARAMETER      :: RootFyc2  = 512
   INTEGER(IntKi), PARAMETER      :: RootFzc2  = 513
   INTEGER(IntKi), PARAMETER      :: RootFxb2  = 514
   INTEGER(IntKi), PARAMETER      :: RootFyb2  = 515
   INTEGER(IntKi), PARAMETER      :: RootMxc2  = 516
   INTEGER(IntKi), PARAMETER      :: RootMyc2  = 517
   INTEGER(IntKi), PARAMETER      :: RootMzc2  = 518
   INTEGER(IntKi), PARAMETER      :: RootMxb2  = 519
   INTEGER(IntKi), PARAMETER      :: RootMyb2  = 520


     ! Blade 3 Root Loads:

   INTEGER(IntKi), PARAMETER      :: RootFxc3  = 521
   INTEGER(IntKi), PARAMETER      :: RootFyc3  = 522
   INTEGER(IntKi), PARAMETER      :: RootFzc3  = 523
   INTEGER(IntKi), PARAMETER      :: RootFxb3  = 524
   INTEGER(IntKi), PARAMETER      :: RootFyb3  = 525
   INTEGER(IntKi), PARAMETER      :: RootMxc3  = 526
   INTEGER(IntKi), PARAMETER      :: RootMyc3  = 527
   INTEGER(IntKi), PARAMETER      :: RootMzc3  = 528
   INTEGER(IntKi), PARAMETER      :: RootMxb3  = 529
   INTEGER(IntKi), PARAMETER      :: RootMyb3  = 530


     ! Blade 1 Local Span Loads:

   INTEGER(IntKi), PARAMETER      :: Spn1MLxb1 = 531
   INTEGER(IntKi), PARAMETER      :: Spn1MLyb1 = 532
   INTEGER(IntKi), PARAMETER      :: Spn1MLzb1 = 533
   INTEGER(IntKi), PARAMETER      :: Spn2MLxb1 = 534
   INTEGER(IntKi), PARAMETER      :: Spn2MLyb1 = 535
   INTEGER(IntKi), PARAMETER      :: Spn2MLzb1 = 536
   INTEGER(IntKi), PARAMETER      :: Spn3MLxb1 = 537
   INTEGER(IntKi), PARAMETER      :: Spn3MLyb1 = 538
   INTEGER(IntKi), PARAMETER      :: Spn3MLzb1 = 539
   INTEGER(IntKi), PARAMETER      :: Spn4MLxb1 = 540
   INTEGER(IntKi), PARAMETER      :: Spn4MLyb1 = 541
   INTEGER(IntKi), PARAMETER      :: Spn4MLzb1 = 542
   INTEGER(IntKi), PARAMETER      :: Spn5MLxb1 = 543
   INTEGER(IntKi), PARAMETER      :: Spn5MLyb1 = 544
   INTEGER(IntKi), PARAMETER      :: Spn5MLzb1 = 545
   INTEGER(IntKi), PARAMETER      :: Spn6MLxb1 = 546
   INTEGER(IntKi), PARAMETER      :: Spn6MLyb1 = 547
   INTEGER(IntKi), PARAMETER      :: Spn6MLzb1 = 548
   INTEGER(IntKi), PARAMETER      :: Spn7MLxb1 = 549
   INTEGER(IntKi), PARAMETER      :: Spn7MLyb1 = 550
   INTEGER(IntKi), PARAMETER      :: Spn7MLzb1 = 551
   INTEGER(IntKi), PARAMETER      :: Spn8MLxb1 = 552
   INTEGER(IntKi), PARAMETER      :: Spn8MLyb1 = 553
   INTEGER(IntKi), PARAMETER      :: Spn8MLzb1 = 554
   INTEGER(IntKi), PARAMETER      :: Spn9MLxb1 = 555
   INTEGER(IntKi), PARAMETER      :: Spn9MLyb1 = 556
   INTEGER(IntKi), PARAMETER      :: Spn9MLzb1 = 557
   INTEGER(IntKi), PARAMETER      :: Spn1FLxb1 = 558
   INTEGER(IntKi), PARAMETER      :: Spn1FLyb1 = 559
   INTEGER(IntKi), PARAMETER      :: Spn1FLzb1 = 560
   INTEGER(IntKi), PARAMETER      :: Spn2FLxb1 = 561
   INTEGER(IntKi), PARAMETER      :: Spn2FLyb1 = 562
   INTEGER(IntKi), PARAMETER      :: Spn2FLzb1 = 563
   INTEGER(IntKi), PARAMETER      :: Spn3FLxb1 = 564
   INTEGER(IntKi), PARAMETER      :: Spn3FLyb1 = 565
   INTEGER(IntKi), PARAMETER      :: Spn3FLzb1 = 566
   INTEGER(IntKi), PARAMETER      :: Spn4FLxb1 = 567
   INTEGER(IntKi), PARAMETER      :: Spn4FLyb1 = 568
   INTEGER(IntKi), PARAMETER      :: Spn4FLzb1 = 569
   INTEGER(IntKi), PARAMETER      :: Spn5FLxb1 = 570
   INTEGER(IntKi), PARAMETER      :: Spn5FLyb1 = 571
   INTEGER(IntKi), PARAMETER      :: Spn5FLzb1 = 572
   INTEGER(IntKi), PARAMETER      :: Spn6FLxb1 = 573
   INTEGER(IntKi), PARAMETER      :: Spn6FLyb1 = 574
   INTEGER(IntKi), PARAMETER      :: Spn6FLzb1 = 575
   INTEGER(IntKi), PARAMETER      :: Spn7FLxb1 = 576
   INTEGER(IntKi), PARAMETER      :: Spn7FLyb1 = 577
   INTEGER(IntKi), PARAMETER      :: Spn7FLzb1 = 578
   INTEGER(IntKi), PARAMETER      :: Spn8FLxb1 = 579
   INTEGER(IntKi), PARAMETER      :: Spn8FLyb1 = 580
   INTEGER(IntKi), PARAMETER      :: Spn8FLzb1 = 581
   INTEGER(IntKi), PARAMETER      :: Spn9FLxb1 = 582
   INTEGER(IntKi), PARAMETER      :: Spn9FLyb1 = 583
   INTEGER(IntKi), PARAMETER      :: Spn9FLzb1 = 584


     ! Blade 2 Local Span Loads:

   INTEGER(IntKi), PARAMETER      :: Spn1MLxb2 = 585
   INTEGER(IntKi), PARAMETER      :: Spn1MLyb2 = 586
   INTEGER(IntKi), PARAMETER      :: Spn1MLzb2 = 587
   INTEGER(IntKi), PARAMETER      :: Spn2MLxb2 = 588
   INTEGER(IntKi), PARAMETER      :: Spn2MLyb2 = 589
   INTEGER(IntKi), PARAMETER      :: Spn2MLzb2 = 590
   INTEGER(IntKi), PARAMETER      :: Spn3MLxb2 = 591
   INTEGER(IntKi), PARAMETER      :: Spn3MLyb2 = 592
   INTEGER(IntKi), PARAMETER      :: Spn3MLzb2 = 593
   INTEGER(IntKi), PARAMETER      :: Spn4MLxb2 = 594
   INTEGER(IntKi), PARAMETER      :: Spn4MLyb2 = 595
   INTEGER(IntKi), PARAMETER      :: Spn4MLzb2 = 596
   INTEGER(IntKi), PARAMETER      :: Spn5MLxb2 = 597
   INTEGER(IntKi), PARAMETER      :: Spn5MLyb2 = 598
   INTEGER(IntKi), PARAMETER      :: Spn5MLzb2 = 599
   INTEGER(IntKi), PARAMETER      :: Spn6MLxb2 = 600
   INTEGER(IntKi), PARAMETER      :: Spn6MLyb2 = 601
   INTEGER(IntKi), PARAMETER      :: Spn6MLzb2 = 602
   INTEGER(IntKi), PARAMETER      :: Spn7MLxb2 = 603
   INTEGER(IntKi), PARAMETER      :: Spn7MLyb2 = 604
   INTEGER(IntKi), PARAMETER      :: Spn7MLzb2 = 605
   INTEGER(IntKi), PARAMETER      :: Spn8MLxb2 = 606
   INTEGER(IntKi), PARAMETER      :: Spn8MLyb2 = 607
   INTEGER(IntKi), PARAMETER      :: Spn8MLzb2 = 608
   INTEGER(IntKi), PARAMETER      :: Spn9MLxb2 = 609
   INTEGER(IntKi), PARAMETER      :: Spn9MLyb2 = 610
   INTEGER(IntKi), PARAMETER      :: Spn9MLzb2 = 611
   INTEGER(IntKi), PARAMETER      :: Spn1FLxb2 = 612
   INTEGER(IntKi), PARAMETER      :: Spn1FLyb2 = 613
   INTEGER(IntKi), PARAMETER      :: Spn1FLzb2 = 614
   INTEGER(IntKi), PARAMETER      :: Spn2FLxb2 = 615
   INTEGER(IntKi), PARAMETER      :: Spn2FLyb2 = 616
   INTEGER(IntKi), PARAMETER      :: Spn2FLzb2 = 617
   INTEGER(IntKi), PARAMETER      :: Spn3FLxb2 = 618
   INTEGER(IntKi), PARAMETER      :: Spn3FLyb2 = 619
   INTEGER(IntKi), PARAMETER      :: Spn3FLzb2 = 620
   INTEGER(IntKi), PARAMETER      :: Spn4FLxb2 = 621
   INTEGER(IntKi), PARAMETER      :: Spn4FLyb2 = 622
   INTEGER(IntKi), PARAMETER      :: Spn4FLzb2 = 623
   INTEGER(IntKi), PARAMETER      :: Spn5FLxb2 = 624
   INTEGER(IntKi), PARAMETER      :: Spn5FLyb2 = 625
   INTEGER(IntKi), PARAMETER      :: Spn5FLzb2 = 626
   INTEGER(IntKi), PARAMETER      :: Spn6FLxb2 = 627
   INTEGER(IntKi), PARAMETER      :: Spn6FLyb2 = 628
   INTEGER(IntKi), PARAMETER      :: Spn6FLzb2 = 629
   INTEGER(IntKi), PARAMETER      :: Spn7FLxb2 = 630
   INTEGER(IntKi), PARAMETER      :: Spn7FLyb2 = 631
   INTEGER(IntKi), PARAMETER      :: Spn7FLzb2 = 632
   INTEGER(IntKi), PARAMETER      :: Spn8FLxb2 = 633
   INTEGER(IntKi), PARAMETER      :: Spn8FLyb2 = 634
   INTEGER(IntKi), PARAMETER      :: Spn8FLzb2 = 635
   INTEGER(IntKi), PARAMETER      :: Spn9FLxb2 = 636
   INTEGER(IntKi), PARAMETER      :: Spn9FLyb2 = 637
   INTEGER(IntKi), PARAMETER      :: Spn9FLzb2 = 638


     ! Blade 3 Local Span Loads:

   INTEGER(IntKi), PARAMETER      :: Spn1MLxb3 = 639
   INTEGER(IntKi), PARAMETER      :: Spn1MLyb3 = 640
   INTEGER(IntKi), PARAMETER      :: Spn1MLzb3 = 641
   INTEGER(IntKi), PARAMETER      :: Spn2MLxb3 = 642
   INTEGER(IntKi), PARAMETER      :: Spn2MLyb3 = 643
   INTEGER(IntKi), PARAMETER      :: Spn2MLzb3 = 644
   INTEGER(IntKi), PARAMETER      :: Spn3MLxb3 = 645
   INTEGER(IntKi), PARAMETER      :: Spn3MLyb3 = 646
   INTEGER(IntKi), PARAMETER      :: Spn3MLzb3 = 647
   INTEGER(IntKi), PARAMETER      :: Spn4MLxb3 = 648
   INTEGER(IntKi), PARAMETER      :: Spn4MLyb3 = 649
   INTEGER(IntKi), PARAMETER      :: Spn4MLzb3 = 650
   INTEGER(IntKi), PARAMETER      :: Spn5MLxb3 = 651
   INTEGER(IntKi), PARAMETER      :: Spn5MLyb3 = 652
   INTEGER(IntKi), PARAMETER      :: Spn5MLzb3 = 653
   INTEGER(IntKi), PARAMETER      :: Spn6MLxb3 = 654
   INTEGER(IntKi), PARAMETER      :: Spn6MLyb3 = 655
   INTEGER(IntKi), PARAMETER      :: Spn6MLzb3 = 656
   INTEGER(IntKi), PARAMETER      :: Spn7MLxb3 = 657
   INTEGER(IntKi), PARAMETER      :: Spn7MLyb3 = 658
   INTEGER(IntKi), PARAMETER      :: Spn7MLzb3 = 659
   INTEGER(IntKi), PARAMETER      :: Spn8MLxb3 = 660
   INTEGER(IntKi), PARAMETER      :: Spn8MLyb3 = 661
   INTEGER(IntKi), PARAMETER      :: Spn8MLzb3 = 662
   INTEGER(IntKi), PARAMETER      :: Spn9MLxb3 = 663
   INTEGER(IntKi), PARAMETER      :: Spn9MLyb3 = 664
   INTEGER(IntKi), PARAMETER      :: Spn9MLzb3 = 665
   INTEGER(IntKi), PARAMETER      :: Spn1FLxb3 = 666
   INTEGER(IntKi), PARAMETER      :: Spn1FLyb3 = 667
   INTEGER(IntKi), PARAMETER      :: Spn1FLzb3 = 668
   INTEGER(IntKi), PARAMETER      :: Spn2FLxb3 = 669
   INTEGER(IntKi), PARAMETER      :: Spn2FLyb3 = 670
   INTEGER(IntKi), PARAMETER      :: Spn2FLzb3 = 671
   INTEGER(IntKi), PARAMETER      :: Spn3FLxb3 = 672
   INTEGER(IntKi), PARAMETER      :: Spn3FLyb3 = 673
   INTEGER(IntKi), PARAMETER      :: Spn3FLzb3 = 674
   INTEGER(IntKi), PARAMETER      :: Spn4FLxb3 = 675
   INTEGER(IntKi), PARAMETER      :: Spn4FLyb3 = 676
   INTEGER(IntKi), PARAMETER      :: Spn4FLzb3 = 677
   INTEGER(IntKi), PARAMETER      :: Spn5FLxb3 = 678
   INTEGER(IntKi), PARAMETER      :: Spn5FLyb3 = 679
   INTEGER(IntKi), PARAMETER      :: Spn5FLzb3 = 680
   INTEGER(IntKi), PARAMETER      :: Spn6FLxb3 = 681
   INTEGER(IntKi), PARAMETER      :: Spn6FLyb3 = 682
   INTEGER(IntKi), PARAMETER      :: Spn6FLzb3 = 683
   INTEGER(IntKi), PARAMETER      :: Spn7FLxb3 = 684
   INTEGER(IntKi), PARAMETER      :: Spn7FLyb3 = 685
   INTEGER(IntKi), PARAMETER      :: Spn7FLzb3 = 686
   INTEGER(IntKi), PARAMETER      :: Spn8FLxb3 = 687
   INTEGER(IntKi), PARAMETER      :: Spn8FLyb3 = 688
   INTEGER(IntKi), PARAMETER      :: Spn8FLzb3 = 689
   INTEGER(IntKi), PARAMETER      :: Spn9FLxb3 = 690
   INTEGER(IntKi), PARAMETER      :: Spn9FLyb3 = 691
   INTEGER(IntKi), PARAMETER      :: Spn9FLzb3 = 692


     ! Hub and Rotor Loads:

   INTEGER(IntKi), PARAMETER      :: LSShftFxa = 693
   INTEGER(IntKi), PARAMETER      :: LSShftFya = 694
   INTEGER(IntKi), PARAMETER      :: LSShftFza = 695
   INTEGER(IntKi), PARAMETER      :: LSShftFys = 696
   INTEGER(IntKi), PARAMETER      :: LSShftFzs = 697
   INTEGER(IntKi), PARAMETER      :: LSShftMxa = 698
   INTEGER(IntKi), PARAMETER      :: LSSTipMya = 699
   INTEGER(IntKi), PARAMETER      :: LSSTipMza = 700
   INTEGER(IntKi), PARAMETER      :: LSSTipMys = 701
   INTEGER(IntKi), PARAMETER      :: LSSTipMzs = 702
   INTEGER(IntKi), PARAMETER      :: RotPwr    = 703


     ! Shaft Strain Gage Loads:

   INTEGER(IntKi), PARAMETER      :: LSSGagMya = 704
   INTEGER(IntKi), PARAMETER      :: LSSGagMza = 705
   INTEGER(IntKi), PARAMETER      :: LSSGagMys = 706
   INTEGER(IntKi), PARAMETER      :: LSSGagMzs = 707


     ! High-Speed Shaft Loads:

   INTEGER(IntKi), PARAMETER      :: HSShftTq  = 708
   INTEGER(IntKi), PARAMETER      :: HSSBrTq   = 709
   INTEGER(IntKi), PARAMETER      :: HSShftPwr = 710


     ! Rotor-Furl Bearing Loads:

   INTEGER(IntKi), PARAMETER      :: RFrlBrM   = 711


     ! Tail-Furl Bearing Loads:

   INTEGER(IntKi), PARAMETER      :: TFrlBrM   = 712


     ! Tower-Top / Yaw Bearing Loads:

   INTEGER(IntKi), PARAMETER      :: YawBrFxn  = 713
   INTEGER(IntKi), PARAMETER      :: YawBrFyn  = 714
   INTEGER(IntKi), PARAMETER      :: YawBrFzn  = 715
   INTEGER(IntKi), PARAMETER      :: YawBrFxp  = 716
   INTEGER(IntKi), PARAMETER      :: YawBrFyp  = 717
   INTEGER(IntKi), PARAMETER      :: YawBrMxn  = 718
   INTEGER(IntKi), PARAMETER      :: YawBrMyn  = 719
   INTEGER(IntKi), PARAMETER      :: YawBrMzn  = 720
   INTEGER(IntKi), PARAMETER      :: YawBrMxp  = 721
   INTEGER(IntKi), PARAMETER      :: YawBrMyp  = 722


     ! Tower Base Loads:

   INTEGER(IntKi), PARAMETER      :: TwrBsFxt  = 723
   INTEGER(IntKi), PARAMETER      :: TwrBsFyt  = 724
   INTEGER(IntKi), PARAMETER      :: TwrBsFzt  = 725
   INTEGER(IntKi), PARAMETER      :: TwrBsMxt  = 726
   INTEGER(IntKi), PARAMETER      :: TwrBsMyt  = 727
   INTEGER(IntKi), PARAMETER      :: TwrBsMzt  = 728


     ! Local Tower Loads:

   INTEGER(IntKi), PARAMETER      :: TwHt1MLxt = 729
   INTEGER(IntKi), PARAMETER      :: TwHt1MLyt = 730
   INTEGER(IntKi), PARAMETER      :: TwHt1MLzt = 731
   INTEGER(IntKi), PARAMETER      :: TwHt2MLxt = 732
   INTEGER(IntKi), PARAMETER      :: TwHt2MLyt = 733
   INTEGER(IntKi), PARAMETER      :: TwHt2MLzt = 734
   INTEGER(IntKi), PARAMETER      :: TwHt3MLxt = 735
   INTEGER(IntKi), PARAMETER      :: TwHt3MLyt = 736
   INTEGER(IntKi), PARAMETER      :: TwHt3MLzt = 737
   INTEGER(IntKi), PARAMETER      :: TwHt4MLxt = 738
   INTEGER(IntKi), PARAMETER      :: TwHt4MLyt = 739
   INTEGER(IntKi), PARAMETER      :: TwHt4MLzt = 740
   INTEGER(IntKi), PARAMETER      :: TwHt5MLxt = 741
   INTEGER(IntKi), PARAMETER      :: TwHt5MLyt = 742
   INTEGER(IntKi), PARAMETER      :: TwHt5MLzt = 743
   INTEGER(IntKi), PARAMETER      :: TwHt6MLxt = 744
   INTEGER(IntKi), PARAMETER      :: TwHt6MLyt = 745
   INTEGER(IntKi), PARAMETER      :: TwHt6MLzt = 746
   INTEGER(IntKi), PARAMETER      :: TwHt7MLxt = 747
   INTEGER(IntKi), PARAMETER      :: TwHt7MLyt = 748
   INTEGER(IntKi), PARAMETER      :: TwHt7MLzt = 749
   INTEGER(IntKi), PARAMETER      :: TwHt8MLxt = 750
   INTEGER(IntKi), PARAMETER      :: TwHt8MLyt = 751
   INTEGER(IntKi), PARAMETER      :: TwHt8MLzt = 752
   INTEGER(IntKi), PARAMETER      :: TwHt9MLxt = 753
   INTEGER(IntKi), PARAMETER      :: TwHt9MLyt = 754
   INTEGER(IntKi), PARAMETER      :: TwHt9MLzt = 755
   INTEGER(IntKi), PARAMETER      :: TwHt1FLxt = 756
   INTEGER(IntKi), PARAMETER      :: TwHt1FLyt = 757
   INTEGER(IntKi), PARAMETER      :: TwHt1FLzt = 758
   INTEGER(IntKi), PARAMETER      :: TwHt2FLxt = 759
   INTEGER(IntKi), PARAMETER      :: TwHt2FLyt = 760
   INTEGER(IntKi), PARAMETER      :: TwHt2FLzt = 761
   INTEGER(IntKi), PARAMETER      :: TwHt3FLxt = 762
   INTEGER(IntKi), PARAMETER      :: TwHt3FLyt = 763
   INTEGER(IntKi), PARAMETER      :: TwHt3FLzt = 764
   INTEGER(IntKi), PARAMETER      :: TwHt4FLxt = 765
   INTEGER(IntKi), PARAMETER      :: TwHt4FLyt = 766
   INTEGER(IntKi), PARAMETER      :: TwHt4FLzt = 767
   INTEGER(IntKi), PARAMETER      :: TwHt5FLxt = 768
   INTEGER(IntKi), PARAMETER      :: TwHt5FLyt = 769
   INTEGER(IntKi), PARAMETER      :: TwHt5FLzt = 770
   INTEGER(IntKi), PARAMETER      :: TwHt6FLxt = 771
   INTEGER(IntKi), PARAMETER      :: TwHt6FLyt = 772
   INTEGER(IntKi), PARAMETER      :: TwHt6FLzt = 773
   INTEGER(IntKi), PARAMETER      :: TwHt7FLxt = 774
   INTEGER(IntKi), PARAMETER      :: TwHt7FLyt = 775
   INTEGER(IntKi), PARAMETER      :: TwHt7FLzt = 776
   INTEGER(IntKi), PARAMETER      :: TwHt8FLxt = 777
   INTEGER(IntKi), PARAMETER      :: TwHt8FLyt = 778
   INTEGER(IntKi), PARAMETER      :: TwHt8FLzt = 779
   INTEGER(IntKi), PARAMETER      :: TwHt9FLxt = 780
   INTEGER(IntKi), PARAMETER      :: TwHt9FLyt = 781
   INTEGER(IntKi), PARAMETER      :: TwHt9FLzt = 782


     ! Internal Degrees of Freedom:

   INTEGER(IntKi), PARAMETER      :: Q_B1E1    = 783
   INTEGER(IntKi), PARAMETER      :: Q_B2E1    = 784
   INTEGER(IntKi), PARAMETER      :: Q_B3E1    = 785
   INTEGER(IntKi), PARAMETER      :: Q_B1F1    = 786
   INTEGER(IntKi), PARAMETER      :: Q_B2F1    = 787
   INTEGER(IntKi), PARAMETER      :: Q_B3F1    = 788
   INTEGER(IntKi), PARAMETER      :: Q_B1F2    = 789
   INTEGER(IntKi), PARAMETER      :: Q_B2F2    = 790
   INTEGER(IntKi), PARAMETER      :: Q_B3F2    = 791
   INTEGER(IntKi), PARAMETER      :: Q_Teet    = 792
   INTEGER(IntKi), PARAMETER      :: Q_DrTr    = 793
   INTEGER(IntKi), PARAMETER      :: Q_GeAz    = 794
   INTEGER(IntKi), PARAMETER      :: Q_RFrl    = 795
   INTEGER(IntKi), PARAMETER      :: Q_TFrl    = 796
   INTEGER(IntKi), PARAMETER      :: Q_Yaw     = 797
   INTEGER(IntKi), PARAMETER      :: Q_TFA1    = 798
   INTEGER(IntKi), PARAMETER      :: Q_TSS1    = 799
   INTEGER(IntKi), PARAMETER      :: Q_TFA2    = 800
   INTEGER(IntKi), PARAMETER      :: Q_TSS2    = 801
   INTEGER(IntKi), PARAMETER      :: Q_Sg      = 802
   INTEGER(IntKi), PARAMETER      :: Q_Sw      = 803
   INTEGER(IntKi), PARAMETER      :: Q_Hv      = 804
   INTEGER(IntKi), PARAMETER      :: Q_R       = 805
   INTEGER(IntKi), PARAMETER      :: Q_P       = 806
   INTEGER(IntKi), PARAMETER      :: Q_Y       = 807
   INTEGER(IntKi), PARAMETER      :: QD_B1E1   = 808
   INTEGER(IntKi), PARAMETER      :: QD_B2E1   = 809
   INTEGER(IntKi), PARAMETER      :: QD_B3E1   = 810
   INTEGER(IntKi), PARAMETER      :: QD_B1F1   = 811
   INTEGER(IntKi), PARAMETER      :: QD_B2F1   = 812
   INTEGER(IntKi), PARAMETER      :: QD_B3F1   = 813
   INTEGER(IntKi), PARAMETER      :: QD_B1F2   = 814
   INTEGER(IntKi), PARAMETER      :: QD_B2F2   = 815
   INTEGER(IntKi), PARAMETER      :: QD_B3F2   = 816
   INTEGER(IntKi), PARAMETER      :: QD_Teet   = 817
   INTEGER(IntKi), PARAMETER      :: QD_DrTr   = 818
   INTEGER(IntKi), PARAMETER      :: QD_GeAz   = 819
   INTEGER(IntKi), PARAMETER      :: QD_RFrl   = 820
   INTEGER(IntKi), PARAMETER      :: QD_TFrl   = 821
   INTEGER(IntKi), PARAMETER      :: QD_Yaw    = 822
   INTEGER(IntKi), PARAMETER      :: QD_TFA1   = 823
   INTEGER(IntKi), PARAMETER      :: QD_TSS1   = 824
   INTEGER(IntKi), PARAMETER      :: QD_TFA2   = 825
   INTEGER(IntKi), PARAMETER      :: QD_TSS2   = 826
   INTEGER(IntKi), PARAMETER      :: QD_Sg     = 827
   INTEGER(IntKi), PARAMETER      :: QD_Sw     = 828
   INTEGER(IntKi), PARAMETER      :: QD_Hv     = 829
   INTEGER(IntKi), PARAMETER      :: QD_R      = 830
   INTEGER(IntKi), PARAMETER      :: QD_P      = 831
   INTEGER(IntKi), PARAMETER      :: QD_Y      = 832
   INTEGER(IntKi), PARAMETER      :: QD2_B1E1  = 833
   INTEGER(IntKi), PARAMETER      :: QD2_B2E1  = 834
   INTEGER(IntKi), PARAMETER      :: QD2_B3E1  = 835
   INTEGER(IntKi), PARAMETER      :: QD2_B1F1  = 836
   INTEGER(IntKi), PARAMETER      :: QD2_B2F1  = 837
   INTEGER(IntKi), PARAMETER      :: QD2_B3F1  = 838
   INTEGER(IntKi), PARAMETER      :: QD2_B1F2  = 839
   INTEGER(IntKi), PARAMETER      :: QD2_B2F2  = 840
   INTEGER(IntKi), PARAMETER      :: QD2_B3F2  = 841
   INTEGER(IntKi), PARAMETER      :: QD2_Teet  = 842
   INTEGER(IntKi), PARAMETER      :: QD2_DrTr  = 843
   INTEGER(IntKi), PARAMETER      :: QD2_GeAz  = 844
   INTEGER(IntKi), PARAMETER      :: QD2_RFrl  = 845
   INTEGER(IntKi), PARAMETER      :: QD2_TFrl  = 846
   INTEGER(IntKi), PARAMETER      :: QD2_Yaw   = 847
   INTEGER(IntKi), PARAMETER      :: QD2_TFA1  = 848
   INTEGER(IntKi), PARAMETER      :: QD2_TSS1  = 849
   INTEGER(IntKi), PARAMETER      :: QD2_TFA2  = 850
   INTEGER(IntKi), PARAMETER      :: QD2_TSS2  = 851
   INTEGER(IntKi), PARAMETER      :: QD2_Sg    = 852
   INTEGER(IntKi), PARAMETER      :: QD2_Sw    = 853
   INTEGER(IntKi), PARAMETER      :: QD2_Hv    = 854
   INTEGER(IntKi), PARAMETER      :: QD2_R     = 855
   INTEGER(IntKi), PARAMETER      :: QD2_P     = 856
   INTEGER(IntKi), PARAMETER      :: QD2_Y     = 857


     ! The maximum number of output channels which can be output by the code.
   INTEGER(IntKi), PARAMETER      :: MaxOutPts = 857

!End of code generated by Matlab script
! ===================================================================================================
