! ===================================================================================================
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these 
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary. 
! ===================================================================================================
! This code was generated by Write_ChckOutLst.m at 23-Apr-2015 13:13:13.


     ! Parameters related to output length (number of characters allowed in the output data headers):

   INTEGER(IntKi), PARAMETER      :: OutStrLenM1 = ChanLen - 1


     ! Indices for computing output channels:
     ! NOTES: 
     !    (1) These parameters are in the order stored in "OutListParameters.xlsx"
     !    (2) Array y%AllOuts() must be dimensioned to the value of the largest output parameter

     !  Time: 

   INTEGER(IntKi), PARAMETER      :: Time      =  0


     ! Wind Motions:

   INTEGER(IntKi), PARAMETER      :: Wind1VelX =  1
   INTEGER(IntKi), PARAMETER      :: Wind1VelY =  2
   INTEGER(IntKi), PARAMETER      :: Wind1VelZ =  3
   INTEGER(IntKi), PARAMETER      :: Wind2VelX =  4
   INTEGER(IntKi), PARAMETER      :: Wind2VelY =  5
   INTEGER(IntKi), PARAMETER      :: Wind2VelZ =  6
   INTEGER(IntKi), PARAMETER      :: Wind3VelX =  7
   INTEGER(IntKi), PARAMETER      :: Wind3VelY =  8
   INTEGER(IntKi), PARAMETER      :: Wind3VelZ =  9
   INTEGER(IntKi), PARAMETER      :: Wind4VelX = 10
   INTEGER(IntKi), PARAMETER      :: Wind4VelY = 11
   INTEGER(IntKi), PARAMETER      :: Wind4VelZ = 12
   INTEGER(IntKi), PARAMETER      :: Wind5VelX = 13
   INTEGER(IntKi), PARAMETER      :: Wind5VelY = 14
   INTEGER(IntKi), PARAMETER      :: Wind5VelZ = 15
   INTEGER(IntKi), PARAMETER      :: Wind6VelX = 16
   INTEGER(IntKi), PARAMETER      :: Wind6VelY = 17
   INTEGER(IntKi), PARAMETER      :: Wind6VelZ = 18
   INTEGER(IntKi), PARAMETER      :: Wind7VelX = 19
   INTEGER(IntKi), PARAMETER      :: Wind7VelY = 20
   INTEGER(IntKi), PARAMETER      :: Wind7VelZ = 21
   INTEGER(IntKi), PARAMETER      :: Wind8VelX = 22
   INTEGER(IntKi), PARAMETER      :: Wind8VelY = 23
   INTEGER(IntKi), PARAMETER      :: Wind8VelZ = 24
   INTEGER(IntKi), PARAMETER      :: Wind9VelX = 25
   INTEGER(IntKi), PARAMETER      :: Wind9VelY = 26
   INTEGER(IntKi), PARAMETER      :: Wind9VelZ = 27


     ! Wind Sensor Measurements:

   INTEGER(IntKi), PARAMETER      :: WindMeas1 = 28
   INTEGER(IntKi), PARAMETER      :: WindMeas2 = 29
   INTEGER(IntKi), PARAMETER      :: WindMeas3 = 30
   INTEGER(IntKi), PARAMETER      :: WindMeas4 = 31
   INTEGER(IntKi), PARAMETER      :: WindMeas5 = 32


     ! The maximum number of output channels which can be output by the code.
   INTEGER(IntKi), PARAMETER      :: MaxOutPts = 32

!End of code generated by Matlab script
! ===================================================================================================
