! ===================================================================================================
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these 
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary. 
! ===================================================================================================
! This code was generated by Write_ChckOutLst.m at 05-Nov-2015 09:57:49.


     ! Parameters related to output length (number of characters allowed in the output data headers):

   INTEGER(IntKi), PARAMETER      :: OutStrLenM1 = ChanLen - 1


     ! Indices for computing output channels:
     ! NOTES: 
     !    (1) These parameters are in the order stored in "OutListParameters.xlsx"
     !    (2) Array AllOuts() must be dimensioned to the value of the largest output parameter

     !  Time: 

   INTEGER(IntKi), PARAMETER      :: Time      =  0


     ! Pitch Control:

   INTEGER(IntKi), PARAMETER      :: BlPitchC1 =  1
   INTEGER(IntKi), PARAMETER      :: BlPitchC2 =  2
   INTEGER(IntKi), PARAMETER      :: BlPitchC3 =  3


     ! Generator and Torque Control:

   INTEGER(IntKi), PARAMETER      :: GenTq     =  4
   INTEGER(IntKi), PARAMETER      :: GenPwr    =  5


     ! High Speed Shaft Brake:

   INTEGER(IntKi), PARAMETER      :: HSSBrTqC  =  6


     ! Nacelle Yaw Control:

   INTEGER(IntKi), PARAMETER      :: YawMomCom =  7


     ! Nacelle Tuned Mass Damper (TMD):

   INTEGER(IntKi), PARAMETER      :: NTMD_XQ   =  8
   INTEGER(IntKi), PARAMETER      :: NTMD_XQD  =  9
   INTEGER(IntKi), PARAMETER      :: NTMD_YQ   = 10
   INTEGER(IntKi), PARAMETER      :: NTMD_YQD  = 11


     ! Tower Tuned Mass Damper (TMD):

   INTEGER(IntKi), PARAMETER      :: TTMD_XQ   = 12
   INTEGER(IntKi), PARAMETER      :: TTMD_XQD  = 13
   INTEGER(IntKi), PARAMETER      :: TTMD_YQ   = 14
   INTEGER(IntKi), PARAMETER      :: TTMD_YQD  = 15


     ! The maximum number of output channels which can be output by the code.
   INTEGER(IntKi), PARAMETER      :: MaxOutPts = 15

!End of code generated by Matlab script
! ===================================================================================================
